/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/core/default_attribute_names.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/default_attribute_names.h>
#include <dew/core/error.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

inline constexpr auto attribute_xyz = DEW_ATTRIBUTE_XYZ;
inline constexpr auto attribute_intensity = DEW_ATTRIBUTE_INTENSITY;
inline constexpr auto attribute_las_composite_0 = DEW_ATTRIBUTE_LAS_COMPOSITE_0;
inline constexpr auto attribute_las_composite_1 = DEW_ATTRIBUTE_LAS_COMPOSITE_1;
inline constexpr auto attribute_las_composite_2 = DEW_ATTRIBUTE_LAS_COMPOSITE_2;
inline constexpr auto attribute_classification = DEW_ATTRIBUTE_CLASSIFICATION;
inline constexpr auto attribute_scan_angle_rank = DEW_ATTRIBUTE_SCAN_ANGLE_RANK;
inline constexpr auto attribute_user_data = DEW_ATTRIBUTE_USER_DATA;
inline constexpr auto attribute_point_source_id = DEW_ATTRIBUTE_POINT_SOURCE_ID;
inline constexpr auto attribute_gps_time = DEW_ATTRIBUTE_GPS_TIME;
inline constexpr auto attribute_rgb = DEW_ATTRIBUTE_RGB;
inline constexpr auto attribute_wave_packet_descriptor_index = DEW_ATTRIBUTE_WAVE_PACKET_DESCRIPTOR_INDEX;
inline constexpr auto attribute_byte_offset_to_waveform_data = DEW_ATTRIBUTE_BYTE_OFFSET_TO_WAVEFORM_DATA;
inline constexpr auto attribute_waveform_packet_size_bytes = DEW_ATTRIBUTE_WAVEFORM_PACKET_SIZE_BYTES;
inline constexpr auto attribute_return_point_waveform_location = DEW_ATTRIBUTE_RETURN_POINT_WAVEFORM_LOCATION;
inline constexpr auto attribute_xyz_t = DEW_ATTRIBUTE_XYZ_T;
inline constexpr auto attribute_scan_angle = DEW_ATTRIBUTE_SCAN_ANGLE;
inline constexpr auto attribute_near_infrared = DEW_ATTRIBUTE_NEAR_INFRARED;
inline constexpr auto attribute_original_order = DEW_ATTRIBUTE_ORIGINAL_ORDER;

} // namespace dewpp
