/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/core/error.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// A VALUE, not a handle.
//
// dew_error_get_info hands back a const char * owned by the dew_error_t, so anything that outlives
// the handle has to copy. Owning the handle instead would work but makes the error move-only, which
// is a poor payload for std::expected. Copy once, at the boundary, and be done.
//
// dew_error_t itself therefore gets no wrapper class here -- it would only ever be a detail of this.
class error_t
{
public:
  error_t() = default;
  error_t(int code, std::string message)
    : _code(code)
    , _message(std::move(message))
  {
  }

  [[nodiscard]] int code() const { return _code; }
  [[nodiscard]] const std::string &message() const { return _message; }
  [[nodiscard]] explicit operator bool() const { return _code != 0 || !_message.empty(); }

private:
  int _code = 0;
  std::string _message;
};

// The return type of anything that can fail. Note again: with -fno-exceptions, .value() on an error
// aborts rather than throwing -- check has_value() first.
template <class T> using result_t = std::expected<T, error_t>;
// For a fallible call with nothing to return.
using status_t = std::expected<void, error_t>;

namespace detail
{
// Copy a dew_error_t into a value. A null handle, or one nobody set, becomes `fallback` -- the C API
// has calls that fail without writing an error, and silently returning a blank one would be worse.
inline error_t read_error(const dew_error_t *handle, const char *fallback)
{
  if (!handle)
    return error_t(-1, fallback);
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return error_t(-1, fallback);
  return error_t(code, std::string(text ? text : "", length));
}

// For an ACCESSOR: is there actually an error in there?
//
// Not the same question as "was a handle written". dew_dataset_get_error / dew_request_get_error go
// through fill_error, which ALWAYS allocates -- it copies the stored error even when that error is
// blank. So a non-null handle proves nothing and only the content can answer.
inline std::optional<error_t> read_error_or_none(const dew_error_t *handle)
{
  if (!handle)
    return std::nullopt;
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return std::nullopt;
  return error_t(code, std::string(text ? text : "", length));
}

// The dew_error_t ** convention: the callee allocates, the caller destroys.
class error_out_t
{
public:
  error_out_t() = default;
  ~error_out_t()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  error_out_t(const error_out_t &) = delete;
  error_out_t &operator=(const error_out_t &) = delete;

  [[nodiscard]] dew_error_t **slot() { return &_handle; }
  [[nodiscard]] bool set() const { return _handle != nullptr; }
  [[nodiscard]] error_t take(const char *fallback) const { return read_error(_handle, fallback); }
  // For accessors, where a written handle does not mean a real error.
  [[nodiscard]] std::optional<error_t> take_if_set() const { return read_error_or_none(_handle); }

private:
  dew_error_t *_handle = nullptr;
};

// The dew_error_t * convention: the CALLER allocates, so the object always exists and its existence
// says nothing. "Did it fail" is `code != 0 || length != 0` -- an untouched dew_error_create() has
// code 0 and an empty (but non-null) message.
class scoped_error_t
{
public:
  scoped_error_t()
    : _handle(dew_error_create())
  {
  }
  ~scoped_error_t()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  scoped_error_t(const scoped_error_t &) = delete;
  scoped_error_t &operator=(const scoped_error_t &) = delete;

  [[nodiscard]] dew_error_t *get() const { return _handle; }
  [[nodiscard]] bool set() const
  {
    if (!_handle)
      return false;
    int code = 0;
    const char *text = nullptr;
    size_t length = 0;
    dew_error_get_info(_handle, &code, &text, &length);
    return code != 0 || length != 0;
  }
  [[nodiscard]] error_t take(const char *fallback) const { return read_error(_handle, fallback); }

private:
  dew_error_t *_handle = nullptr;
};

// The two-call convention behind every `..._get_*_name(handle, index, buf, capacity)`: ask with a
// buffer, and grow if the answer did not fit. Starting at 256 means one call in practice.
template <class Fn> inline std::string out_string(Fn &&call)
{
  std::string buffer(256, '\0');
  uint32_t written = call(buffer.data(), uint32_t(buffer.size()));
  if (written > buffer.size())
  {
    buffer.resize(written);
    written = call(buffer.data(), uint32_t(buffer.size()));
  }
  buffer.resize(written < buffer.size() ? written : buffer.size());
  return buffer;
}
} // namespace detail

} // namespace dewpp
