/* GENERATED by tools/bindgen/generate_cpp_await.py -- do not edit.
 *
 * dew/core/pump_async.hpp -- the pump, driven from a vio event loop, as coroutines.
 *
 * dewfall never calls user code on its own threads: it raises ONE wake per burst of completions, and
 * the host dispatches them with dew_pump_poll on a thread of its choosing. This is that handshake:
 *
 *     #include <dew/access/query_async.hpp>
 *     #include <vio/run.h>
 *
 *     VIO_MAIN(loop, argc, argv)
 *     {
 *       dewpp::async::driver_t driver(loop);
 *       dew_error_t *error = nullptr;
 *       auto *dataset = dew_dataset_create(url, len, nullptr, 0, nullptr, driver.pump(), &error);
 *       if (co_await dewpp::async::ready(driver, dataset) != dew_dataset_ready)
 *         co_return 1;
 *       ...
 *     }
 *
 * Header-only and inline: include it, link the public C API, bring your own vio loop. This is the one
 * part of the C++ wrapper that needs vio, which is why it is a separate file -- a caller with no
 * event loop includes the sync headers and never pays for it.
 *
 * THREADING. The wake fires on an arbitrary internal thread -- and under wasm possibly re-entrantly,
 * because there the loop is cooperative rather than a separate thread. It may therefore only SIGNAL,
 * which is exactly what it does: post to the loop and return. Everything else (dew_pump_poll, the
 * waiter list, resuming coroutines) happens on the loop thread, which is what makes the awaiters free
 * of locks. Await only from coroutines running on the driver's own loop.
 */
#pragma once

#include <dew/core/pump.h>

#include <vio/event_loop.h>

#include <coroutine>
#include <functional>
#include <utility>
#include <vector>

namespace dewpp::async
{

// Owns the pump/loop wiring. One driver drives any number of datasets and requests: the pump is
// shared, which is what it is for -- a single wake, and a single poll that drains everything.
class driver_t
{
public:
  // Creates and owns a pump.
  explicit driver_t(vio::event_loop_t &loop)
    : _loop(loop)
    , _pump(dew_pump_create())
    , _owns_pump(true)
  {
    dew_pump_set_wake_callback(_pump, &driver_t::on_wake, this);
  }

  // Borrows an existing pump, for a host that already has one.
  driver_t(vio::event_loop_t &loop, dew_pump_t *pump)
    : _loop(loop)
    , _pump(pump)
    , _owns_pump(false)
  {
    dew_pump_set_wake_callback(_pump, &driver_t::on_wake, this);
  }

  ~driver_t()
  {
    // Detach BEFORE anything else: passing null waits out a wake that is already in flight, so a late
    // completion cannot post into a half-destroyed driver.
    dew_pump_set_wake_callback(_pump, nullptr, nullptr);
    if (_owns_pump)
      dew_pump_destroy(_pump);
  }

  driver_t(const driver_t &) = delete;
  driver_t &operator=(const driver_t &) = delete;

  // Pass this to dew_dataset_create. Note that dew_dataset_poll returns 0 on a dataset sharing a
  // pump -- draining one subsystem of a shared pump is the partial drain that loses wakeups. Poll the
  // pump, which is what drain() does.
  [[nodiscard]] dew_pump_t *pump() const { return _pump; }
  [[nodiscard]] vio::event_loop_t &event_loop() const { return _loop; }

  // Dispatch, then resume whatever became ready. Public because a host with its own frame loop (a
  // renderer, say) may prefer to drive it from there rather than wait to be woken.
  void drain()
  {
    dew_pump_poll(_pump);
    // Resume from a snapshot: a resumed coroutine runs to its next suspension immediately and may
    // register a new waiter, which would invalidate an iterator over the live vector.
    std::vector<std::coroutine_handle<>> ready;
    for (size_t i = 0; i < _waiters.size();)
    {
      if (_waiters[i].predicate())
      {
        ready.push_back(_waiters[i].continuation);
        _waiters[i] = std::move(_waiters.back());
        _waiters.pop_back();
      }
      else
      {
        ++i;
      }
    }
    for (auto continuation : ready)
      continuation.resume();
  }

  // co_await until `predicate` holds. The generated ready() overloads below are thin wrappers around
  // this; use it directly for a condition the annotations do not describe.
  class awaiter_t
  {
  public:
    awaiter_t(driver_t &driver, std::function<bool()> predicate)
      : _driver(driver)
      , _predicate(std::move(predicate))
    {
    }

    bool await_ready() const { return _predicate(); }

    void await_suspend(std::coroutine_handle<> continuation) { _driver._waiters.push_back({_predicate, continuation}); }

    void await_resume() const {}

  private:
    driver_t &_driver;
    std::function<bool()> _predicate;
  };

  awaiter_t until(std::function<bool()> predicate) { return awaiter_t(*this, std::move(predicate)); }

  // The seam the generated awaiters use to park themselves. Loop thread only, like everything else
  // here: a coroutine awaiting from another thread would race drain().
  void await_register(std::function<bool()> predicate, std::coroutine_handle<> continuation) { _waiters.push_back({std::move(predicate), continuation}); }

private:
  static void on_wake(void *user_ptr)
  {
    // ARBITRARY THREAD, possibly re-entrant under wasm. Post and return -- that is the entire legal
    // vocabulary here. run_in_loop is thread-safe, which is what makes this sound.
    auto *self = static_cast<driver_t *>(user_ptr);
    self->_loop.run_in_loop([self]() { self->drain(); });
  }

  struct waiter_t
  {
    std::function<bool()> predicate;
    std::coroutine_handle<> continuation;
  };

  vio::event_loop_t &_loop;
  dew_pump_t *_pump;
  bool _owns_pump;
  std::vector<waiter_t> _waiters;
};

} // namespace dewpp::async
