/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/core/pump.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/core/pump.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class pump_t;

// Owns its dew_pump_t: move-only, destroyed with dew_pump_destroy.
class pump_t
{
public:
  pump_t() = default;
  explicit pump_t(dew_pump_t *handle)
    : _handle(handle)
  {
  }

  ~pump_t() { reset(); }
  pump_t(pump_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  pump_t &operator=(pump_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  pump_t(const pump_t &) = delete;
  pump_t &operator=(const pump_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_pump_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_pump_t *release()
  {
    dew_pump_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_pump_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<pump_t> create();

  //  Replaces any previous callback and rearms. Pass NULL to stop being woken; polling still works.
  void set_wake_callback(dew_wake_callback_t callback, void * callback_user_ptr) const;

  //  Rearm the wake, then dispatch everything pending. Returns the number of events dispatched.
  //
  //  Host thread only, and it is where every subsystem callback runs.
  //
  //  The rearm happens BEFORE the dispatch, deliberately. Rearming afterwards would lose wakeups: a
  //  completion landing mid-dispatch would call the wake, find it still raised from the wake that
  //  caused this poll, be suppressed -- and then the rearm would clear the signal, leaving queued work
  //  with nothing to announce it. Rearming first costs the occasional redundant wake instead, which is
  //  the right way round.
  uint32_t poll() const;

  //  Events waiting to be dispatched. A host that drives the pump from a timer can use this to decide
  //  whether another tick is worth scheduling.
  uint32_t pending_count() const;

private:
  dew_pump_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<pump_t> pump_t::create()
{
  dew_pump_t *handle_ = dew_pump_create();
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_pump_create failed"));
  return pump_t(handle_);
}

inline void pump_t::set_wake_callback(dew_wake_callback_t callback, void * callback_user_ptr) const
{
  dew_pump_set_wake_callback(_handle, callback, callback_user_ptr);
}

inline uint32_t pump_t::poll() const
{
  uint32_t return_ = dew_pump_poll(_handle);
  return return_;
}

inline uint32_t pump_t::pending_count() const
{
  uint32_t return_ = dew_pump_pending_count(_handle);
  return return_;
}

} // namespace dewpp
