/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/core/types.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/core/format.h>
#include <dew/core/types.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using attribute_t = dew_attribute_t;
using blob_t = dew_blob_t;

class attributes_t;

//  Opaque, append-only attribute set. Built by the file-convert `init` callback and consumed by the
//  attribute registry; the C++ definition lives with the internal dataset types.
// A BORROWED dew_attributes_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class attributes_t
{
public:
  attributes_t() = default;
  explicit attributes_t(dew_attributes_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_attributes_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void add_attribute(std::string_view name, dew_type_t format, dew_components_t components) const;

private:
  dew_attributes_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline void attributes_t::add_attribute(std::string_view name, dew_type_t format, dew_components_t components) const
{
  dew_attributes_add_attribute(_handle, name.data(), static_cast<uint32_t>(name.size()), format, components);
}

} // namespace dewpp
