/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * A header-only C++ wrapper for dewfall's public C API, in namespace `dewpp`.
 *
 * The C API is shaped for an ABI: opaque handles, out-parameters, caller-allocated dew_error_t **,
 * (pointer, length) string pairs, explicit destroy calls. This is the same API with the tedium
 * removed -- RAII handles, std::string_view in, std::string out, errors returned by value:
 *
 *     auto opened = dewpp::converter::create("out.dew", dew_open_file_semantics_truncate);
 *     if (!opened)
 *       return fail(opened.error().message());
 *     dewpp::converter conv = std::move(*opened);
 *     conv.add_data_file(files);
 *     conv.wait_idle();
 *
 * ERRORS, WITHOUT EXCEPTIONS. dewfall builds -fno-exceptions, so a failing constructor cannot report
 * by throwing -- which is why handles are created through static factories returning
 * `dewpp::result<T>` (std::expected<T, dewpp::error>). BEWARE: with exceptions disabled,
 * std::expected::value() on an error cannot throw and will abort instead. Check has_value(), or
 * dereference only once you have.
 *
 * OWNERSHIP. Owning handles are move-only and destroy on scope exit; `release()` hands the raw
 * handle back if you need to escape the wrapper. A few handles are BORROWED views the library owns
 * (attributes, buffer, to_render) -- those are copyable, destroy nothing, and are only valid for as
 * long as whatever handed them to you says they are.
 *
 * ALIASED, NOT REWRAPPED. Enums, value structs and constants are `using` aliases of the C types. A
 * parallel enum class would be a second source of truth that can drift, and conversions would buy
 * nothing. Callback structs and function pointers are likewise passed through as the C types,
 * because the C API's single void* user_ptr is the caller's to spend.
 */
#pragma once

#include <dew/core/error.h>
#include <dew/core/types.h>
#include <dew/core/pump.h>
#include <dew/render/buffer.h>
#include <dew/render/camera.h>
#include <dew/render/data_source.h>
#include <dew/render/renderer.h>
#include <dew/render/aabb_data_source.h>
#include <dew/render/axis_gizmo_data_source.h>
#include <dew/render/environment_data_source.h>
#include <dew/render/flat_points_data_source.h>
#include <dew/render/origin_anchor_data_source.h>
#include <dew/render/skybox_data_source.h>
#include <dew/access/query.h>
#include <dew/converter/converter.h>
#include <dew/converter/converter_data_source.h>
#include <dew/core/format.h>
#include <dew/render/draw_group.h>
#include <dew/render/aabb.h>
#include <dew/converter/laszip_file_convert_callbacks.h>
#include <dew/core/default_attribute_names.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// A VALUE, not a handle.
//
// dew_error_get_info hands back a const char * owned by the dew_error_t, so anything that outlives
// the handle has to copy. Owning the handle instead would work but makes the error move-only, which
// is a poor payload for std::expected. Copy once, at the boundary, and be done.
//
// dew_error_t itself therefore gets no wrapper class here -- it would only ever be a detail of this.
class error
{
public:
  error() = default;
  error(int code, std::string message)
    : _code(code)
    , _message(std::move(message))
  {
  }

  [[nodiscard]] int code() const { return _code; }
  [[nodiscard]] const std::string &message() const { return _message; }
  [[nodiscard]] explicit operator bool() const { return _code != 0 || !_message.empty(); }

private:
  int _code = 0;
  std::string _message;
};

// The return type of anything that can fail. Note again: with -fno-exceptions, .value() on an error
// aborts rather than throwing -- check has_value() first.
template <class T> using result = std::expected<T, error>;
// For a fallible call with nothing to return.
using status = std::expected<void, error>;

namespace detail
{
// Copy a dew_error_t into a value. A null handle, or one nobody set, becomes `fallback` -- the C API
// has calls that fail without writing an error, and silently returning a blank one would be worse.
inline error read_error(const dew_error_t *handle, const char *fallback)
{
  if (!handle)
    return error(-1, fallback);
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return error(-1, fallback);
  return error(code, std::string(text ? text : "", length));
}

// For an ACCESSOR: is there actually an error in there?
//
// Not the same question as "was a handle written". dew_dataset_get_error / dew_request_get_error go
// through fill_error, which ALWAYS allocates -- it copies the stored error even when that error is
// blank. So a non-null handle proves nothing and only the content can answer.
inline std::optional<error> read_error_or_none(const dew_error_t *handle)
{
  if (!handle)
    return std::nullopt;
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return std::nullopt;
  return error(code, std::string(text ? text : "", length));
}

// The dew_error_t ** convention: the callee allocates, the caller destroys.
class error_out
{
public:
  error_out() = default;
  ~error_out()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  error_out(const error_out &) = delete;
  error_out &operator=(const error_out &) = delete;

  [[nodiscard]] dew_error_t **slot() { return &_handle; }
  [[nodiscard]] bool set() const { return _handle != nullptr; }
  [[nodiscard]] error take(const char *fallback) const { return read_error(_handle, fallback); }
  // For accessors, where a written handle does not mean a real error.
  [[nodiscard]] std::optional<error> take_if_set() const { return read_error_or_none(_handle); }

private:
  dew_error_t *_handle = nullptr;
};

// The dew_error_t * convention: the CALLER allocates, so the object always exists and its existence
// says nothing. "Did it fail" is `code != 0 || length != 0` -- an untouched dew_error_create() has
// code 0 and an empty (but non-null) message.
class scoped_error
{
public:
  scoped_error()
    : _handle(dew_error_create())
  {
  }
  ~scoped_error()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  scoped_error(const scoped_error &) = delete;
  scoped_error &operator=(const scoped_error &) = delete;

  [[nodiscard]] dew_error_t *get() const { return _handle; }
  [[nodiscard]] bool set() const
  {
    if (!_handle)
      return false;
    int code = 0;
    const char *text = nullptr;
    size_t length = 0;
    dew_error_get_info(_handle, &code, &text, &length);
    return code != 0 || length != 0;
  }
  [[nodiscard]] error take(const char *fallback) const { return read_error(_handle, fallback); }

private:
  dew_error_t *_handle = nullptr;
};

// The two-call convention behind every `..._get_*_name(handle, index, buf, capacity)`: ask with a
// buffer, and grow if the answer did not fit. Starting at 256 means one call in practice.
template <class Fn> inline std::string out_string(Fn &&call)
{
  std::string buffer(256, '\0');
  uint32_t written = call(buffer.data(), uint32_t(buffer.size()));
  if (written > buffer.size())
  {
    buffer.resize(written);
    written = call(buffer.data(), uint32_t(buffer.size()));
  }
  buffer.resize(written < buffer.size() ? written : buffer.size());
  return buffer;
}
} // namespace detail

// ---- enums, value structs and constants: aliases of the C declarations ----

using type = dew_type_t;
using components = dew_components_t;
using draw_type = dew_draw_type_t;
using buffer_type = dew_buffer_type_t;
using texture_type = dew_texture_type_t;
using aabb_mesh_buffer_mapping = dew_aabb_mesh_buffer_mapping_t;
using skybox_buffer_mapping = dew_skybox_buffer_mapping_t;
using buffer_mapping = dew_buffer_mapping_t;
using dyn_points_buffer_mapping = dew_dyn_points_buffer_mapping_t;
using axis_gizmo_buffer_mapping = dew_axis_gizmo_buffer_mapping_t;
using origin_anchor_buffer_mapping = dew_origin_anchor_buffer_mapping_t;
using environment_buffer_mapping = dew_environment_buffer_mapping_t;
using node_bbox_buffer_mapping = dew_node_bbox_buffer_mapping_t;
using dataset_state = dew_dataset_state_t;
using request_status = dew_request_status_t;
using lod_mode = dew_lod_mode_t;
using clip_mode = dew_clip_mode_t;
using position_format = dew_position_format_t;
using converter_conversion_status = dew_converter_conversion_status_t;
using converter_open_file_semantics = dew_converter_open_file_semantics_t;
using converter_compression = dew_converter_compression_t;

using attribute = dew_attribute_t;
using blob = dew_blob_t;
using aabb = dew_aabb_t;
using draw_buffer = dew_draw_buffer_t;
using draw_group = dew_draw_group_t;
using frame_camera = dew_frame_camera_t;
using data_source = dew_data_source_t;
using frame = dew_frame_t;
using renderer_callbacks = dew_renderer_callbacks_t;
using skybox_data = dew_skybox_data_t;
using dataset_options = dew_dataset_options_t;
using dataset_info = dew_dataset_info_t;
using region_request = dew_region_request_t;
using attribute_buffer = dew_attribute_buffer_t;
using result_node = dew_result_node_t;
using request_result = dew_request_result_t;
using converter_header = dew_converter_header_t;
using converter_file_pre_init_info = dew_converter_file_pre_init_info_t;
using converter_file_convert_callbacks = dew_converter_file_convert_callbacks_t;
using converter_runtime_callbacks = dew_converter_runtime_callbacks_t;
using converter_upload_callbacks = dew_converter_upload_callbacks_t;
using converter_upload_state = dew_converter_upload_state_t;
using converter_buffer_callbacks = dew_converter_buffer_callbacks_t;
using converter_str_buffer = dew_converter_str_buffer;
using converter_attribute_stats = dew_converter_attribute_stats_t;
using converter_stats = dew_converter_stats_t;
using converter_io_stats = dew_converter_io_stats_t;
using converter_perf_stats = dew_converter_perf_stats_t;

inline constexpr auto attribute_xyz = DEW_ATTRIBUTE_XYZ;
inline constexpr auto attribute_intensity = DEW_ATTRIBUTE_INTENSITY;
inline constexpr auto attribute_las_composite_0 = DEW_ATTRIBUTE_LAS_COMPOSITE_0;
inline constexpr auto attribute_las_composite_1 = DEW_ATTRIBUTE_LAS_COMPOSITE_1;
inline constexpr auto attribute_las_composite_2 = DEW_ATTRIBUTE_LAS_COMPOSITE_2;
inline constexpr auto attribute_classification = DEW_ATTRIBUTE_CLASSIFICATION;
inline constexpr auto attribute_scan_angle_rank = DEW_ATTRIBUTE_SCAN_ANGLE_RANK;
inline constexpr auto attribute_user_data = DEW_ATTRIBUTE_USER_DATA;
inline constexpr auto attribute_point_source_id = DEW_ATTRIBUTE_POINT_SOURCE_ID;
inline constexpr auto attribute_gps_time = DEW_ATTRIBUTE_GPS_TIME;
inline constexpr auto attribute_rgb = DEW_ATTRIBUTE_RGB;
inline constexpr auto attribute_wave_packet_descriptor_index = DEW_ATTRIBUTE_WAVE_PACKET_DESCRIPTOR_INDEX;
inline constexpr auto attribute_byte_offset_to_waveform_data = DEW_ATTRIBUTE_BYTE_OFFSET_TO_WAVEFORM_DATA;
inline constexpr auto attribute_waveform_packet_size_bytes = DEW_ATTRIBUTE_WAVEFORM_PACKET_SIZE_BYTES;
inline constexpr auto attribute_return_point_waveform_location = DEW_ATTRIBUTE_RETURN_POINT_WAVEFORM_LOCATION;
inline constexpr auto attribute_xyz_t = DEW_ATTRIBUTE_XYZ_T;
inline constexpr auto attribute_scan_angle = DEW_ATTRIBUTE_SCAN_ANGLE;
inline constexpr auto attribute_near_infrared = DEW_ATTRIBUTE_NEAR_INFRARED;
inline constexpr auto attribute_original_order = DEW_ATTRIBUTE_ORIGINAL_ORDER;

// ---- handles ----

class attributes;
class pump;
class buffer;
class camera;
class arcball;
class fps;
class to_render;
class renderer;
class aabb_data_source;
class axis_gizmo_data_source;
class environment_data_source;
class flat_points_data_source;
class origin_anchor_data_source;
class skybox_data_source;
class dataset;
class request;
class converter;
class converter_data_source;

//  Opaque, append-only attribute set. Built by the file-convert `init` callback and consumed by the
//  attribute registry; the C++ definition lives with the internal dataset types.
// A BORROWED dew_attributes_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class attributes
{
public:
  attributes() = default;
  explicit attributes(dew_attributes_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_attributes_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void add_attribute(std::string_view name, dew_type_t format, dew_components_t components) const;

private:
  dew_attributes_t *_handle = nullptr;
};

// Owns its dew_pump_t: move-only, destroyed with dew_pump_destroy.
class pump
{
public:
  pump() = default;
  explicit pump(dew_pump_t *handle)
    : _handle(handle)
  {
  }

  ~pump() { reset(); }
  pump(pump &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  pump &operator=(pump &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  pump(const pump &) = delete;
  pump &operator=(const pump &) = delete;

  void reset()
  {
    if (_handle)
      dew_pump_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_pump_t *release()
  {
    dew_pump_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_pump_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<pump> create();

  //  Replaces any previous callback and rearms. Pass NULL to stop being woken; polling still works.
  void set_wake_callback(dew_wake_callback_t callback, void * callback_user_ptr) const;

  //  Rearm the wake, then dispatch everything pending. Returns the number of events dispatched.
  //
  //  Host thread only, and it is where every subsystem callback runs.
  //
  //  The rearm happens BEFORE the dispatch, deliberately. Rearming afterwards would lose wakeups: a
  //  completion landing mid-dispatch would call the wake, find it still raised from the wake that
  //  caused this poll, be suppressed -- and then the rearm would clear the signal, leaving queued work
  //  with nothing to announce it. Rearming first costs the occasional redundant wake instead, which is
  //  the right way round.
  uint32_t poll() const;

  //  Events waiting to be dispatched. A host that drives the pump from a timer can use this to decide
  //  whether another tick is worth scheduling.
  uint32_t pending_count() const;

private:
  dew_pump_t *_handle = nullptr;
};

// A BORROWED dew_buffer_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class buffer
{
public:
  buffer() = default;
  explicit buffer(dew_buffer_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_buffer_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void set_rendered() const;

  void release_data() const;

private:
  dew_buffer_t *_handle = nullptr;
};

struct camera_perspective_properties_result
{
  double fov;
  double aspect;
  double near;
  double far;
};

// Owns its dew_camera_t: move-only, destroyed with dew_camera_destroy.
class camera
{
public:
  camera() = default;
  explicit camera(dew_camera_t *handle)
    : _handle(handle)
  {
  }

  ~camera() { reset(); }
  camera(camera &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  camera &operator=(camera &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  camera(const camera &) = delete;
  camera &operator=(const camera &) = delete;

  void reset()
  {
    if (_handle)
      dew_camera_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_camera_t *release()
  {
    dew_camera_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_camera_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<camera> create();

  void look_at(const std::array<double, 3> & eye, const std::array<double, 3> & center, const std::array<double, 3> & up) const;

  void look_at_aabb(const dew_aabb_t & aabb, const std::array<double, 3> & direction, const std::array<double, 3> & up) const;

  std::array<double, 16> get_view_matrix() const;

  void set_view_matrix(const std::array<double, 16> & data) const;

  std::array<double, 16> get_perspective_matrix() const;

  void set_perspective_matrix(const std::array<double, 16> & data) const;

  void set_perspective(double fov, double width, double height, double near, double far) const;

  camera_perspective_properties_result perspective_properties() const;

  std::array<double, 3> get_eye() const;

  std::array<double, 3> get_forward() const;

private:
  dew_camera_t *_handle = nullptr;
};

// Owns its dew_arcball_t: move-only, destroyed with dew_arcball_destroy.
class arcball
{
public:
  arcball() = default;
  explicit arcball(dew_arcball_t *handle)
    : _handle(handle)
  {
  }

  ~arcball() { reset(); }
  arcball(arcball &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  arcball &operator=(arcball &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  arcball(const arcball &) = delete;
  arcball &operator=(const arcball &) = delete;

  void reset()
  {
    if (_handle)
      dew_arcball_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_arcball_t *release()
  {
    dew_arcball_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_arcball_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<arcball> create(const camera & camera, const std::array<double, 3> & center);

  void reset() const;

  void detect_upside_down() const;

  void rotate(float normalized_dx, float normalized_dy, float normalized_dz) const;

  void pan(float normalized_dx, float normalized_dy) const;

  void pan_ground(float normalized_dx, float normalized_dy) const;

  void dolly(float normalized_dz) const;

  void zoom(float normalized_zoom) const;

  void set_up_axis(const std::array<double, 3> & up) const;

  std::array<double, 3> get_up_axis() const;

  std::array<double, 3> get_center() const;

private:
  dew_arcball_t *_handle = nullptr;
};

// Owns its dew_fps_t: move-only, destroyed with dew_fps_destroy.
class fps
{
public:
  fps() = default;
  explicit fps(dew_fps_t *handle)
    : _handle(handle)
  {
  }

  ~fps() { reset(); }
  fps(fps &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  fps &operator=(fps &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  fps(const fps &) = delete;
  fps &operator=(const fps &) = delete;

  void reset()
  {
    if (_handle)
      dew_fps_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_fps_t *release()
  {
    dew_fps_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_fps_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<fps> create(const camera & camera);

  void reset() const;

  void rotate(float normalized_dx, float normalized_dy, float normalized_dz) const;

  void move(float dx, float dy, float dz) const;

private:
  dew_fps_t *_handle = nullptr;
};

// A BORROWED dew_to_render_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class to_render
{
public:
  to_render() = default;
  explicit to_render(dew_to_render_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_to_render_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void add_render_group(const dew_draw_group_t & draw_group) const;

private:
  dew_to_render_t *_handle = nullptr;
};

// Owns its dew_renderer_t: move-only, destroyed with dew_renderer_destroy.
class renderer
{
public:
  renderer() = default;
  explicit renderer(dew_renderer_t *handle)
    : _handle(handle)
  {
  }

  ~renderer() { reset(); }
  renderer(renderer &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  renderer &operator=(renderer &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  renderer(const renderer &) = delete;
  renderer &operator=(const renderer &) = delete;

  void reset()
  {
    if (_handle)
      dew_renderer_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_renderer_t *release()
  {
    dew_renderer_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_renderer_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<renderer> create();

  void add_camera(const camera & camera) const;

  void remove_camera(const camera & camera) const;

  dew_frame_t frame(const camera & camera) const;

  void set_callback(dew_renderer_callbacks_t callbacks, void * callbacks_user_ptr) const;

  void add_data_source(const dew_data_source_t & data_source) const;

  void remove_data_source(const dew_data_source_t & data_source) const;

private:
  dew_renderer_t *_handle = nullptr;
};

// Owns its dew_aabb_data_source_t: move-only, destroyed with dew_aabb_data_source_destroy.
class aabb_data_source
{
public:
  aabb_data_source() = default;
  explicit aabb_data_source(dew_aabb_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~aabb_data_source() { reset(); }
  aabb_data_source(aabb_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  aabb_data_source &operator=(aabb_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  aabb_data_source(const aabb_data_source &) = delete;
  aabb_data_source &operator=(const aabb_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_aabb_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_aabb_data_source_t *release()
  {
    dew_aabb_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_aabb_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<aabb_data_source> create(const renderer & renderer, const std::array<double, 3> & offset);

  dew_data_source_t get() const;

  int add_aabb(const std::array<double, 3> & min, const std::array<double, 3> & max) const;

  void remove_aabb(int id) const;

  void modify_aabb(int id, const std::array<double, 3> & min, const std::array<double, 3> & max) const;

  std::array<double, 3> get_center(int id) const;

private:
  dew_aabb_data_source_t *_handle = nullptr;
};

// Owns its dew_axis_gizmo_data_source_t: move-only, destroyed with dew_axis_gizmo_data_source_destroy.
class axis_gizmo_data_source
{
public:
  axis_gizmo_data_source() = default;
  explicit axis_gizmo_data_source(dew_axis_gizmo_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~axis_gizmo_data_source() { reset(); }
  axis_gizmo_data_source(axis_gizmo_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  axis_gizmo_data_source &operator=(axis_gizmo_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  axis_gizmo_data_source(const axis_gizmo_data_source &) = delete;
  axis_gizmo_data_source &operator=(const axis_gizmo_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_axis_gizmo_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_axis_gizmo_data_source_t *release()
  {
    dew_axis_gizmo_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_axis_gizmo_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<axis_gizmo_data_source> create(const renderer & renderer, const std::array<double, 3> & center, double axis_length);

  dew_data_source_t get() const;

  void set_center(const std::array<double, 3> & center) const;

  void set_axis_length(double axis_length) const;

private:
  dew_axis_gizmo_data_source_t *_handle = nullptr;
};

// Owns its dew_environment_data_source_t: move-only, destroyed with dew_environment_data_source_destroy.
class environment_data_source
{
public:
  environment_data_source() = default;
  explicit environment_data_source(dew_environment_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~environment_data_source() { reset(); }
  environment_data_source(environment_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  environment_data_source &operator=(environment_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  environment_data_source(const environment_data_source &) = delete;
  environment_data_source &operator=(const environment_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_environment_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_environment_data_source_t *release()
  {
    dew_environment_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_environment_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<environment_data_source> create(const renderer & renderer, double ground_z, double grid_size);

  dew_data_source_t get() const;

  void set_ground_z(double ground_z) const;

private:
  dew_environment_data_source_t *_handle = nullptr;
};

struct flat_points_data_source_get_aabb_result
{
  std::array<double, 3> aabb_min;
  std::array<double, 3> aabb_max;
};

// Owns its dew_flat_points_data_source_t: move-only, destroyed with dew_flat_points_data_source_destroy.
class flat_points_data_source
{
public:
  flat_points_data_source() = default;
  explicit flat_points_data_source(dew_flat_points_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~flat_points_data_source() { reset(); }
  flat_points_data_source(flat_points_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  flat_points_data_source &operator=(flat_points_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  flat_points_data_source(const flat_points_data_source &) = delete;
  flat_points_data_source &operator=(const flat_points_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_flat_points_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_flat_points_data_source_t *release()
  {
    dew_flat_points_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_flat_points_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<flat_points_data_source> create(const renderer & renderer, std::string_view url);

  dew_data_source_t get() const;

  flat_points_data_source_get_aabb_result get_aabb() const;

private:
  dew_flat_points_data_source_t *_handle = nullptr;
};

// Owns its dew_origin_anchor_data_source_t: move-only, destroyed with dew_origin_anchor_data_source_destroy.
class origin_anchor_data_source
{
public:
  origin_anchor_data_source() = default;
  explicit origin_anchor_data_source(dew_origin_anchor_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~origin_anchor_data_source() { reset(); }
  origin_anchor_data_source(origin_anchor_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  origin_anchor_data_source &operator=(origin_anchor_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  origin_anchor_data_source(const origin_anchor_data_source &) = delete;
  origin_anchor_data_source &operator=(const origin_anchor_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_origin_anchor_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_origin_anchor_data_source_t *release()
  {
    dew_origin_anchor_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_origin_anchor_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<origin_anchor_data_source> create(const renderer & renderer, const std::array<double, 3> & center, double arrow_size);

  dew_data_source_t get() const;

  void set_center(const std::array<double, 3> & center) const;

  void set_arrow_size(double arrow_size) const;

private:
  dew_origin_anchor_data_source_t *_handle = nullptr;
};

// Owns its dew_skybox_data_source_t: move-only, destroyed with dew_skybox_data_source_destroy.
class skybox_data_source
{
public:
  skybox_data_source() = default;
  explicit skybox_data_source(dew_skybox_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~skybox_data_source() { reset(); }
  skybox_data_source(skybox_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  skybox_data_source &operator=(skybox_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  skybox_data_source(const skybox_data_source &) = delete;
  skybox_data_source &operator=(const skybox_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_skybox_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_skybox_data_source_t *release()
  {
    dew_skybox_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_skybox_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<skybox_data_source> create(const renderer & renderer, const dew_skybox_data_t & data);

  dew_data_source_t get() const;

private:
  dew_skybox_data_source_t *_handle = nullptr;
};

//  Awaiting these two.
//
//  The whole protocol is one line each: keep looking until poll(handle) != pending. dew_dataset_t is
//  `opening` until the index read lands; dew_request_t is `pending` until the query finishes. The pump
//  guarantees a wake when either changes, so a poll after that wake is a pure read -- no completion
//  callback has to outlive the handle, and nothing has to be retracted when a caller loses interest.
//
//  tools/bindgen turns these into await wrappers: dew/await/dew_await.hpp for C++ coroutines and
//  dew.aio for Python. Adding an awaitable handle is this annotation and nothing else.
// A BORROWED dew_dataset_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class dataset
{
public:
  dataset() = default;
  explicit dataset(dew_dataset_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_dataset_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  //  Returns immediately with the dataset in `opening`; `error` is only set for arguments that cannot
  //  be used at all. A missing or corrupt dataset surfaces as state == dew_dataset_error, so that the
  //  failure path is the same on native and under wasm, where opening cannot block.
  //
  //  `pump` is where completions are delivered. Pass one to drive several subsystems from a single
  //  wake, or NULL to have the dataset own a private pump -- in which case dew_dataset_poll drives it
  //  and you need not know the pump exists.
  static result<dataset> create(std::string_view url, std::string_view connection, const dew_dataset_options_t & options, const pump & pump);

  void close() const;

  dew_dataset_state_t state() const;

  std::optional<error> get_error() const;

  //  Dispatch this dataset's completions on the calling thread; returns how many were dispatched.
  //
  //  Only valid on a dataset with a PRIVATE pump (created with pump == NULL). On a dataset sharing a
  //  pump it returns 0 -- draining one subsystem of a shared pump is exactly the partial drain that
  //  loses wakeups, so call dew_pump_poll instead.
  uint32_t poll() const;

  uint32_t pending_count() const;

  dew_dataset_state_t wait_ready(int32_t timeout_ms) const;

  dew_dataset_info_t get_info() const;

  uint32_t attribute_count() const;

  std::string get_attribute_name(uint32_t index) const;

private:
  dew_dataset_t *_handle = nullptr;
};

struct request_get_result_result
{
  uint8_t return_;
  dew_request_result_t out;
};

// A BORROWED dew_request_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class request
{
public:
  request() = default;
  explicit request(dew_request_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_request_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  dew_request_status_t status() const;

  dew_request_status_t wait(int32_t timeout_ms) const;

  void cancel() const;

  std::optional<error> get_error() const;

  void release() const;

  float completion_factor() const;

  request_get_result_result get_result() const;

  uint64_t attribute_size(uint32_t attribute_index) const;

  // Not wrapped -- call the C function directly with get():
  //   dew_request_copy_attribute

private:
  dew_request_t *_handle = nullptr;
};

// Owns its dew_converter_t: move-only, destroyed with dew_converter_destroy.
class converter
{
public:
  converter() = default;
  explicit converter(dew_converter_t *handle)
    : _handle(handle)
  {
  }

  ~converter() { reset(); }
  converter(converter &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  converter &operator=(converter &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  converter(const converter &) = delete;
  converter &operator=(const converter &) = delete;

  void reset()
  {
    if (_handle)
      dew_converter_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_converter_t *release()
  {
    dew_converter_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_converter_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<converter> create(std::string_view cache_filename, dew_converter_open_file_semantics_t open_file_semantics);

  //  As dew_converter_create, but first applies `connection` (a vendor connection string -- credentials /
  //  endpoint / region; see connection_cli.h + vio connection_string.h) for the output URL's provider, so a
  //  dataset can be written directly to a cloud store. `connection` may be null/empty for local outputs or
  //  when credentials come from the environment. `open_file_semantics` is typically truncate.
  static result<converter> create_with_connection(std::string_view url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics);

  //  Destination mode: convert into a LOCAL cache file (`cache_path`, a bare path or file:// URL) while
  //  finalized subtrees upload incrementally to `destination_url` (s3:// az:// dir://; DEW2 layout).
  //  The cache stays a valid, renderable DEW at every checkpoint; blobs already uploaded are evicted
  //  from it under the cache cap (see dew_converter_set_cache_max_bytes), and when the disk runs out
  //  mid-conversion, unfinished data spills to the destination's spill/ area and is fetched back on
  //  demand. A null/empty destination degrades to dew_converter_create. `connection` carries the
  //  destination's credentials (null/empty = environment). Reopening the same cache+destination resumes:
  //  committed bands are never re-uploaded (a destination belonging to a different dataset generation is
  //  refused via the embedded uuid).
  static result<converter> create_with_destination(std::string_view cache_path, std::string_view destination_url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics);

  //  Cache-file resident-bytes cap for destination mode. 0 = unlimited (the default). Callable any
  //  time; lowering it triggers eviction/spill passes.
  void set_cache_max_bytes(uint64_t max_bytes) const;

  //  In-RAM decompressed read-cache budget (default 256MB). Also the seam a render/query consumer tunes.
  void set_read_cache_bytes(uint64_t max_bytes) const;

  void set_upload_callbacks(dew_converter_upload_callbacks_t callbacks, void * callbacks_user_ptr) const;

  //  Snapshot of upload/cache-tier state (approximate counters; safe any time). Returns false when the
  //  converter has no destination configured.
  std::optional<dew_converter_upload_state_t> get_upload_state() const;

  //  Wait until conversion is complete and the cache file is a fully checkpointed, valid DEW --
  //  uploads may still be in flight (contrast dew_converter_wait_idle, which also drains them).
  void wait_local_complete() const;

  void set_file_converter_callbacks(dew_converter_file_convert_callbacks_t callbacks) const;

  void set_runtime_callbacks(dew_converter_runtime_callbacks_t callbacks, void * callbacks_user_ptr) const;

  void set_compression(dew_converter_compression_t compression) const;

  void set_store_original_order(bool store) const;

  void set_compression_level(int level) const;

  //  Set the target points per octree node. This doubles as the read/sort chunk size, so it is the main
  //  control over stored blob size (one node ~ one compressed blob per attribute). Default 200000. Must be
  //  called before dew_converter_add_data_file.
  void set_node_point_limit(uint32_t points) const;

  //  Explicitly pin the octree coordinate scale (a single value used for all three axes). Without this the
  //  converter adopts the finest native scale of the first batch of input files (LAS header scale), falling
  //  back to 0.00025 when the source reports none. Must be called before dew_converter_add_data_file.
  void set_tree_scale(double scale) const;

  //  LOD nodes carry only the visual attributes (position + rgb/intensity/classification) by default;
  //  pass 1 to duplicate EVERY source attribute into every LOD level (the pre-slimming behavior, at a
  //  substantial size cost). Must be called before dew_converter_add_data_file.
  void set_lod_all_attributes(uint8_t all) const;

  //  Read/sort chunk byte target (default 64 MiB): the converter ingests each input in chunks of about
  //  this many bytes (computed from the file's per-point width, never below the node point limit,
  //  capped at 8M points per chunk). Larger chunks amortize source reads and sorting; the octree still
  //  subdivides to node_point_limit leaves and finalized leaves are rewritten into per-node units.
  //  Must be called before dew_converter_add_data_file.
  void set_read_chunk_bytes(uint64_t bytes) const;

  //  May block on ingest backpressure, so Python bindings must release the GIL around it.
  void add_data_file(const std::vector<dew_converter_str_buffer> & buffers) const;

  void wait_idle() const;

  dew_converter_conversion_status_t status() const;

  std::optional<dew_converter_stats_t> get_compression_stats() const;

  std::optional<dew_converter_perf_stats_t> get_perf_stats() const;

  std::optional<dew_converter_perf_stats_t> get_live_perf_stats() const;

private:
  dew_converter_t *_handle = nullptr;
};

struct converter_data_source_get_memory_stats_result
{
  uint64_t heap_bytes;
  uint64_t heap_max;
  uint64_t budget_bytes;
  uint64_t backlog_bytes;
  uint64_t read_cache_bytes;
  uint64_t resident_cpu_bytes;
  uint32_t brake_level;
};

struct converter_data_source_get_frame_timings_result
{
  double tree_walk_ms;
  double buffer_reconciliation_ms;
  double gpu_upload_ms;
  double refine_strategy_ms;
  double frontier_scheduling_ms;
  double draw_emission_ms;
  double eviction_ms;
  double total_ms;
  int registry_node_count;
  int active_set_size;
  int nodes_drawn;
  int transitioning_count;
  int nodes_evicted;
  int nodes_reconcile_destroyed;
  int walker_node_count;
  uint64_t walker_total_points;
  int walker_trees_to_load;
  int io_in_flight;
};

struct converter_data_source_get_virtual_stats_result
{
  uint32_t promoted;
  uint64_t gpu_bytes;
  uint64_t resident_cpu_bytes;
  uint32_t nodes_drawn;
};

struct converter_data_source_get_tight_aabb_result
{
  std::array<double, 3> min;
  std::array<double, 3> max;
};

// Owns its dew_converter_data_source_t: move-only, destroyed with dew_converter_data_source_destroy.
class converter_data_source
{
public:
  converter_data_source() = default;
  explicit converter_data_source(dew_converter_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~converter_data_source() { reset(); }
  converter_data_source(converter_data_source &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  converter_data_source &operator=(converter_data_source &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  converter_data_source(const converter_data_source &) = delete;
  converter_data_source &operator=(const converter_data_source &) = delete;

  void reset()
  {
    if (_handle)
      dew_converter_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_converter_data_source_t *release()
  {
    dew_converter_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_converter_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result<converter_data_source> create(std::string_view url, const renderer & renderer);

  //  As dew_converter_data_source_create, but first applies `connection` (a vendor connection string --
  //  credentials / endpoint / region; same grammar/keys as dew_converter_create_with_connection, see vio
  //  connection_string.h) for the dataset URL's provider, so a dataset can be streamed directly from a cloud
  //  store (s3://bucket/prefix, az://container/prefix). `connection` may be null/empty for local files
  //  (file://, bare paths) or when credentials come from the AWS_*/AZURE_* environment; for a public bucket
  //  pass "anonymous=true" (optionally with "region=..."). A no-op for local/dir/mem URLs.
  static result<converter_data_source> create_with_connection(std::string_view url, std::string_view connection, const renderer & renderer);

  dew_data_source_t get() const;

  void request_aabb(dew_converter_data_source_request_aabb_callback_t callback, void * callback_user_ptr) const;

  uint32_t attribute_count() const;

  std::string get_attribute_name(int index) const;

  void set_rendered_attribute(std::string_view name) const;

  void set_viewport(int width, int height) const;

  void set_pixel_error_threshold(double threshold) const;

  void set_render_density_px(double density_px) const;

  void set_gpu_memory_budget(size_t budget_bytes) const;

  void set_upload_budget_per_frame(size_t budget_bytes) const;

  void set_max_in_flight_io(int max_requests) const;

  //  One total CPU-memory budget for the streaming renderer. Internally derived into the read-cache size, the
  //  decoded-backlog byte cap (new IO is refused while estimated in-flight + decoded-awaiting-upload bytes
  //  exceed it), the virtual-subtree CPU-resident budget, and a clamp on max_in_flight_io (see
  //  memory_budget.hpp for the formula). GPU memory has its own budget
  //  (dew_converter_data_source_set_gpu_memory_budget) -- GL buffers live outside this heap. The default
  //  (1GB) reproduces the historical sub-budget defaults. Values below 64MB are clamped up to 64MB.
  void set_memory_budget(uint64_t total_bytes) const;

  uint64_t get_memory_budget() const;

  //  Observability for the memory budget and the wasm heap-pressure brake. heap_bytes/heap_max are the wasm
  //  heap size and its link-time ceiling as probed on the last rendered frame (0/0 on native); backlog_bytes
  //  is the estimated CPU held by in-flight + decoded-awaiting-upload nodes last frame; brake_level is
  //  0 none / 1 high (>=80% of ceiling) / 2 critical (>=90%). Any out-pointer may be null.
  converter_data_source_get_memory_stats_result get_memory_stats() const;

  uint64_t get_points_rendered() const;

  uint8_t is_animating() const;

  converter_data_source_get_frame_timings_result get_frame_timings() const;

  void set_debug_transitions(uint8_t enabled) const;

  //  Virtual subnodes (render-time balanced LOD for spanning leaves). Toggling off tears every virtual cut down
  //  and falls the leaves back to their monoliths, so it is a live A/B on one camera path.
  void set_enable_virtual_subtrees(uint8_t enabled) const;

  uint8_t get_enable_virtual_subtrees() const;

  //  Observability: how many spanning leaves are currently promoted, the GPU bytes their virtual nodes hold, the
  //  CPU bytes their resident sources pin, and how many virtual nodes were drawn last frame.
  converter_data_source_get_virtual_stats_result get_virtual_stats() const;

  void set_show_bounding_boxes(uint8_t enabled) const;

  dew_data_source_t get_bbox_data_source() const;

  converter_data_source_get_tight_aabb_result get_tight_aabb() const;

private:
  dew_converter_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's get() needs that wrapper to be a
// complete type, and the classes reference each other in both directions.

inline void attributes::add_attribute(std::string_view name, dew_type_t format, dew_components_t components) const
{
  dew_attributes_add_attribute(_handle, name.data(), static_cast<uint32_t>(name.size()), format, components);
}

inline result<pump> pump::create()
{
  dew_pump_t *handle_ = dew_pump_create();
  if (!handle_)
    return std::unexpected(error(-1, "dew_pump_create failed"));
  return pump(handle_);
}

inline void pump::set_wake_callback(dew_wake_callback_t callback, void * callback_user_ptr) const
{
  dew_pump_set_wake_callback(_handle, callback, callback_user_ptr);
}

inline uint32_t pump::poll() const
{
  uint32_t return_ = dew_pump_poll(_handle);
  return return_;
}

inline uint32_t pump::pending_count() const
{
  uint32_t return_ = dew_pump_pending_count(_handle);
  return return_;
}

inline void buffer::set_rendered() const
{
  dew_buffer_set_rendered(_handle);
}

inline void buffer::release_data() const
{
  dew_buffer_release_data(_handle);
}

inline result<camera> camera::create()
{
  dew_camera_t *handle_ = dew_camera_create();
  if (!handle_)
    return std::unexpected(error(-1, "dew_camera_create failed"));
  return camera(handle_);
}

inline void camera::look_at(const std::array<double, 3> & eye, const std::array<double, 3> & center, const std::array<double, 3> & up) const
{
  dew_camera_look_at(_handle, eye.data(), center.data(), up.data());
}

inline void camera::look_at_aabb(const dew_aabb_t & aabb, const std::array<double, 3> & direction, const std::array<double, 3> & up) const
{
  dew_camera_look_at_aabb(_handle, const_cast<dew_aabb_t *>(&aabb), direction.data(), up.data());
}

inline std::array<double, 16> camera::get_view_matrix() const
{
  std::array<double, 16> data_out{};
  dew_camera_get_view_matrix(_handle, data_out.data());
  return data_out;
}

inline void camera::set_view_matrix(const std::array<double, 16> & data) const
{
  dew_camera_set_view_matrix(_handle, data.data());
}

inline std::array<double, 16> camera::get_perspective_matrix() const
{
  std::array<double, 16> data_out{};
  dew_camera_get_perspective_matrix(_handle, data_out.data());
  return data_out;
}

inline void camera::set_perspective_matrix(const std::array<double, 16> & data) const
{
  dew_camera_set_perspective_matrix(_handle, data.data());
}

inline void camera::set_perspective(double fov, double width, double height, double near, double far) const
{
  dew_camera_set_perspective(_handle, fov, width, height, near, far);
}

inline camera_perspective_properties_result camera::perspective_properties() const
{
  double fov_out{};
  double aspect_out{};
  double near_out{};
  double far_out{};
  dew_camera_perspective_properties(_handle, &fov_out, &aspect_out, &near_out, &far_out);
  return camera_perspective_properties_result{fov_out, aspect_out, near_out, far_out};
}

inline std::array<double, 3> camera::get_eye() const
{
  std::array<double, 3> eye_out{};
  dew_camera_get_eye(_handle, eye_out.data());
  return eye_out;
}

inline std::array<double, 3> camera::get_forward() const
{
  std::array<double, 3> forward_out{};
  dew_camera_get_forward(_handle, forward_out.data());
  return forward_out;
}

inline result<arcball> arcball::create(const camera & camera, const std::array<double, 3> & center)
{
  dew_arcball_t *handle_ = dew_arcball_create(camera.handle(), center.data());
  if (!handle_)
    return std::unexpected(error(-1, "dew_arcball_create failed"));
  return arcball(handle_);
}

inline void arcball::reset() const
{
  dew_arcball_reset(_handle);
}

inline void arcball::detect_upside_down() const
{
  dew_arcball_detect_upside_down(_handle);
}

inline void arcball::rotate(float normalized_dx, float normalized_dy, float normalized_dz) const
{
  dew_arcball_rotate(_handle, normalized_dx, normalized_dy, normalized_dz);
}

inline void arcball::pan(float normalized_dx, float normalized_dy) const
{
  dew_arcball_pan(_handle, normalized_dx, normalized_dy);
}

inline void arcball::pan_ground(float normalized_dx, float normalized_dy) const
{
  dew_arcball_pan_ground(_handle, normalized_dx, normalized_dy);
}

inline void arcball::dolly(float normalized_dz) const
{
  dew_arcball_dolly(_handle, normalized_dz);
}

inline void arcball::zoom(float normalized_zoom) const
{
  dew_arcball_zoom(_handle, normalized_zoom);
}

inline void arcball::set_up_axis(const std::array<double, 3> & up) const
{
  dew_arcball_set_up_axis(_handle, up.data());
}

inline std::array<double, 3> arcball::get_up_axis() const
{
  std::array<double, 3> up_out{};
  dew_arcball_get_up_axis(_handle, up_out.data());
  return up_out;
}

inline std::array<double, 3> arcball::get_center() const
{
  std::array<double, 3> center_out{};
  dew_arcball_get_center(_handle, center_out.data());
  return center_out;
}

inline result<fps> fps::create(const camera & camera)
{
  dew_fps_t *handle_ = dew_fps_create(camera.handle());
  if (!handle_)
    return std::unexpected(error(-1, "dew_fps_create failed"));
  return fps(handle_);
}

inline void fps::reset() const
{
  dew_fps_reset(_handle);
}

inline void fps::rotate(float normalized_dx, float normalized_dy, float normalized_dz) const
{
  dew_fps_rotate(_handle, normalized_dx, normalized_dy, normalized_dz);
}

inline void fps::move(float dx, float dy, float dz) const
{
  dew_fps_move(_handle, dx, dy, dz);
}

inline void to_render::add_render_group(const dew_draw_group_t & draw_group) const
{
  dew_to_render_add_render_group(_handle, draw_group);
}

inline result<renderer> renderer::create()
{
  dew_renderer_t *handle_ = dew_renderer_create();
  if (!handle_)
    return std::unexpected(error(-1, "dew_renderer_create failed"));
  return renderer(handle_);
}

inline void renderer::add_camera(const camera & camera) const
{
  dew_renderer_add_camera(_handle, camera.handle());
}

inline void renderer::remove_camera(const camera & camera) const
{
  dew_renderer_remove_camera(_handle, camera.handle());
}

inline dew_frame_t renderer::frame(const camera & camera) const
{
  dew_frame_t return_ = dew_renderer_frame(_handle, camera.handle());
  return return_;
}

inline void renderer::set_callback(dew_renderer_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_renderer_set_callback(_handle, callbacks, callbacks_user_ptr);
}

inline void renderer::add_data_source(const dew_data_source_t & data_source) const
{
  dew_renderer_add_data_source(_handle, data_source);
}

inline void renderer::remove_data_source(const dew_data_source_t & data_source) const
{
  dew_renderer_remove_data_source(_handle, data_source);
}

inline result<aabb_data_source> aabb_data_source::create(const renderer & renderer, const std::array<double, 3> & offset)
{
  dew_aabb_data_source_t *handle_ = dew_aabb_data_source_create(renderer.handle(), offset.data());
  if (!handle_)
    return std::unexpected(error(-1, "dew_aabb_data_source_create failed"));
  return aabb_data_source(handle_);
}

inline dew_data_source_t aabb_data_source::get() const
{
  dew_data_source_t return_ = dew_aabb_data_source_get(_handle);
  return return_;
}

inline int aabb_data_source::add_aabb(const std::array<double, 3> & min, const std::array<double, 3> & max) const
{
  int return_ = dew_aabb_data_source_add_aabb(_handle, min.data(), max.data());
  return return_;
}

inline void aabb_data_source::remove_aabb(int id) const
{
  dew_aabb_data_source_remove_aabb(_handle, id);
}

inline void aabb_data_source::modify_aabb(int id, const std::array<double, 3> & min, const std::array<double, 3> & max) const
{
  dew_aabb_data_source_modify_aabb(_handle, id, min.data(), max.data());
}

inline std::array<double, 3> aabb_data_source::get_center(int id) const
{
  std::array<double, 3> center_out{};
  dew_aabb_data_source_get_center(_handle, id, center_out.data());
  return center_out;
}

inline result<axis_gizmo_data_source> axis_gizmo_data_source::create(const renderer & renderer, const std::array<double, 3> & center, double axis_length)
{
  dew_axis_gizmo_data_source_t *handle_ = dew_axis_gizmo_data_source_create(renderer.handle(), center.data(), axis_length);
  if (!handle_)
    return std::unexpected(error(-1, "dew_axis_gizmo_data_source_create failed"));
  return axis_gizmo_data_source(handle_);
}

inline dew_data_source_t axis_gizmo_data_source::get() const
{
  dew_data_source_t return_ = dew_axis_gizmo_data_source_get(_handle);
  return return_;
}

inline void axis_gizmo_data_source::set_center(const std::array<double, 3> & center) const
{
  dew_axis_gizmo_data_source_set_center(_handle, center.data());
}

inline void axis_gizmo_data_source::set_axis_length(double axis_length) const
{
  dew_axis_gizmo_data_source_set_axis_length(_handle, axis_length);
}

inline result<environment_data_source> environment_data_source::create(const renderer & renderer, double ground_z, double grid_size)
{
  dew_environment_data_source_t *handle_ = dew_environment_data_source_create(renderer.handle(), ground_z, grid_size);
  if (!handle_)
    return std::unexpected(error(-1, "dew_environment_data_source_create failed"));
  return environment_data_source(handle_);
}

inline dew_data_source_t environment_data_source::get() const
{
  dew_data_source_t return_ = dew_environment_data_source_get(_handle);
  return return_;
}

inline void environment_data_source::set_ground_z(double ground_z) const
{
  dew_environment_data_source_set_ground_z(_handle, ground_z);
}

inline result<flat_points_data_source> flat_points_data_source::create(const renderer & renderer, std::string_view url)
{
  dew_flat_points_data_source_t *handle_ = dew_flat_points_data_source_create(renderer.handle(), url.data(), static_cast<int>(url.size()));
  if (!handle_)
    return std::unexpected(error(-1, "dew_flat_points_data_source_create failed"));
  return flat_points_data_source(handle_);
}

inline dew_data_source_t flat_points_data_source::get() const
{
  dew_data_source_t return_ = dew_flat_points_data_source_get(_handle);
  return return_;
}

inline flat_points_data_source_get_aabb_result flat_points_data_source::get_aabb() const
{
  std::array<double, 3> aabb_min_out{};
  std::array<double, 3> aabb_max_out{};
  dew_flat_points_get_aabb(_handle, aabb_min_out.data(), aabb_max_out.data());
  return flat_points_data_source_get_aabb_result{aabb_min_out, aabb_max_out};
}

inline result<origin_anchor_data_source> origin_anchor_data_source::create(const renderer & renderer, const std::array<double, 3> & center, double arrow_size)
{
  dew_origin_anchor_data_source_t *handle_ = dew_origin_anchor_data_source_create(renderer.handle(), center.data(), arrow_size);
  if (!handle_)
    return std::unexpected(error(-1, "dew_origin_anchor_data_source_create failed"));
  return origin_anchor_data_source(handle_);
}

inline dew_data_source_t origin_anchor_data_source::get() const
{
  dew_data_source_t return_ = dew_origin_anchor_data_source_get(_handle);
  return return_;
}

inline void origin_anchor_data_source::set_center(const std::array<double, 3> & center) const
{
  dew_origin_anchor_data_source_set_center(_handle, center.data());
}

inline void origin_anchor_data_source::set_arrow_size(double arrow_size) const
{
  dew_origin_anchor_data_source_set_arrow_size(_handle, arrow_size);
}

inline result<skybox_data_source> skybox_data_source::create(const renderer & renderer, const dew_skybox_data_t & data)
{
  dew_skybox_data_source_t *handle_ = dew_skybox_data_source_create(renderer.handle(), data);
  if (!handle_)
    return std::unexpected(error(-1, "dew_skybox_data_source_create failed"));
  return skybox_data_source(handle_);
}

inline dew_data_source_t skybox_data_source::get() const
{
  dew_data_source_t return_ = dew_skybox_data_source_get(_handle);
  return return_;
}

inline result<dataset> dataset::create(std::string_view url, std::string_view connection, const dew_dataset_options_t & options, const pump & pump)
{
  detail::error_out error_;
  dew_dataset_t *handle_ = dew_dataset_create(url.data(), static_cast<uint32_t>(url.size()), connection.data(), static_cast<uint32_t>(connection.size()), &options, pump.handle(), error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_dataset_create failed"));
  return dataset(handle_);
}

inline void dataset::close() const
{
  dew_dataset_close(_handle);
}

inline dew_dataset_state_t dataset::state() const
{
  dew_dataset_state_t return_ = dew_dataset_state(_handle);
  return return_;
}

inline std::optional<error> dataset::get_error() const
{
  detail::error_out error_;
  dew_dataset_get_error(_handle, error_.slot());
  return error_.take_if_set();
}

inline uint32_t dataset::poll() const
{
  uint32_t return_ = dew_dataset_poll(_handle);
  return return_;
}

inline uint32_t dataset::pending_count() const
{
  uint32_t return_ = dew_dataset_pending_count(_handle);
  return return_;
}

inline dew_dataset_state_t dataset::wait_ready(int32_t timeout_ms) const
{
  dew_dataset_state_t return_ = dew_dataset_wait_ready(_handle, timeout_ms);
  return return_;
}

inline dew_dataset_info_t dataset::get_info() const
{
  dew_dataset_info_t info_out{};
  dew_dataset_get_info(_handle, &info_out);
  return info_out;
}

inline uint32_t dataset::attribute_count() const
{
  uint32_t return_ = dew_dataset_attribute_count(_handle);
  return return_;
}

inline std::string dataset::get_attribute_name(uint32_t index) const
{
  return detail::out_string([&](char *buffer_, uint32_t capacity_) {
    return dew_dataset_get_attribute_name(_handle, index, buffer_, capacity_);
  });
}

inline dew_request_status_t request::status() const
{
  dew_request_status_t return_ = dew_request_status(_handle);
  return return_;
}

inline dew_request_status_t request::wait(int32_t timeout_ms) const
{
  dew_request_status_t return_ = dew_request_wait(_handle, timeout_ms);
  return return_;
}

inline void request::cancel() const
{
  dew_request_cancel(_handle);
}

inline std::optional<error> request::get_error() const
{
  detail::error_out error_;
  dew_request_get_error(_handle, error_.slot());
  return error_.take_if_set();
}

inline void request::release() const
{
  dew_request_release(_handle);
}

inline float request::completion_factor() const
{
  float return_ = dew_request_completion_factor(_handle);
  return return_;
}

inline request_get_result_result request::get_result() const
{
  dew_request_result_t out_out{};
  uint8_t return_ = dew_request_get_result(_handle, &out_out);
  return request_get_result_result{return_, out_out};
}

inline uint64_t request::attribute_size(uint32_t attribute_index) const
{
  uint64_t return_ = dew_request_attribute_size(_handle, attribute_index);
  return return_;
}

inline result<converter> converter::create(std::string_view cache_filename, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out error_;
  dew_converter_t *handle_ = dew_converter_create(cache_filename.data(), static_cast<uint64_t>(cache_filename.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create failed"));
  return converter(handle_);
}

inline result<converter> converter::create_with_connection(std::string_view url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out error_;
  dew_converter_t *handle_ = dew_converter_create_with_connection(url.data(), static_cast<uint64_t>(url.size()), connection.data(), static_cast<uint64_t>(connection.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create_with_connection failed"));
  return converter(handle_);
}

inline result<converter> converter::create_with_destination(std::string_view cache_path, std::string_view destination_url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out error_;
  dew_converter_t *handle_ = dew_converter_create_with_destination(cache_path.data(), static_cast<uint64_t>(cache_path.size()), destination_url.data(), static_cast<uint64_t>(destination_url.size()), connection.data(), static_cast<uint64_t>(connection.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create_with_destination failed"));
  return converter(handle_);
}

inline void converter::set_cache_max_bytes(uint64_t max_bytes) const
{
  dew_converter_set_cache_max_bytes(_handle, max_bytes);
}

inline void converter::set_read_cache_bytes(uint64_t max_bytes) const
{
  dew_converter_set_read_cache_bytes(_handle, max_bytes);
}

inline void converter::set_upload_callbacks(dew_converter_upload_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_converter_set_upload_callbacks(_handle, callbacks, callbacks_user_ptr);
}

inline std::optional<dew_converter_upload_state_t> converter::get_upload_state() const
{
  dew_converter_upload_state_t state_out{};
  bool ok_ = dew_converter_get_upload_state(_handle, &state_out);
  return ok_ ? std::optional<dew_converter_upload_state_t>(state_out) : std::nullopt;
}

inline void converter::wait_local_complete() const
{
  dew_converter_wait_local_complete(_handle);
}

inline void converter::set_file_converter_callbacks(dew_converter_file_convert_callbacks_t callbacks) const
{
  dew_converter_set_file_converter_callbacks(_handle, callbacks);
}

inline void converter::set_runtime_callbacks(dew_converter_runtime_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_converter_set_runtime_callbacks(_handle, callbacks, callbacks_user_ptr);
}

inline void converter::set_compression(dew_converter_compression_t compression) const
{
  dew_converter_set_compression(_handle, compression);
}

inline void converter::set_store_original_order(bool store) const
{
  dew_converter_set_store_original_order(_handle, store);
}

inline void converter::set_compression_level(int level) const
{
  dew_converter_set_compression_level(_handle, level);
}

inline void converter::set_node_point_limit(uint32_t points) const
{
  dew_converter_set_node_point_limit(_handle, points);
}

inline void converter::set_tree_scale(double scale) const
{
  dew_converter_set_tree_scale(_handle, scale);
}

inline void converter::set_lod_all_attributes(uint8_t all) const
{
  dew_converter_set_lod_all_attributes(_handle, all);
}

inline void converter::set_read_chunk_bytes(uint64_t bytes) const
{
  dew_converter_set_read_chunk_bytes(_handle, bytes);
}

inline void converter::add_data_file(const std::vector<dew_converter_str_buffer> & buffers) const
{
  dew_converter_add_data_file(_handle, const_cast<dew_converter_str_buffer *>(buffers.data()), static_cast<uint32_t>(buffers.size()));
}

inline void converter::wait_idle() const
{
  dew_converter_wait_idle(_handle);
}

inline dew_converter_conversion_status_t converter::status() const
{
  dew_converter_conversion_status_t return_ = dew_converter_status(_handle);
  return return_;
}

inline std::optional<dew_converter_stats_t> converter::get_compression_stats() const
{
  dew_converter_stats_t stats_out{};
  bool ok_ = dew_converter_get_compression_stats(_handle, &stats_out);
  return ok_ ? std::optional<dew_converter_stats_t>(stats_out) : std::nullopt;
}

inline std::optional<dew_converter_perf_stats_t> converter::get_perf_stats() const
{
  dew_converter_perf_stats_t perf_stats_out{};
  bool ok_ = dew_converter_get_perf_stats(_handle, &perf_stats_out);
  return ok_ ? std::optional<dew_converter_perf_stats_t>(perf_stats_out) : std::nullopt;
}

inline std::optional<dew_converter_perf_stats_t> converter::get_live_perf_stats() const
{
  dew_converter_perf_stats_t perf_stats_out{};
  bool ok_ = dew_converter_get_live_perf_stats(_handle, &perf_stats_out);
  return ok_ ? std::optional<dew_converter_perf_stats_t>(perf_stats_out) : std::nullopt;
}

inline result<converter_data_source> converter_data_source::create(std::string_view url, const renderer & renderer)
{
  detail::scoped_error error_;
  dew_converter_data_source_t *handle_ = dew_converter_data_source_create(url.data(), static_cast<uint32_t>(url.size()), error_.get(), renderer.handle());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_data_source_create failed"));
  return converter_data_source(handle_);
}

inline result<converter_data_source> converter_data_source::create_with_connection(std::string_view url, std::string_view connection, const renderer & renderer)
{
  detail::scoped_error error_;
  dew_converter_data_source_t *handle_ = dew_converter_data_source_create_with_connection(url.data(), static_cast<uint32_t>(url.size()), connection.data(), static_cast<uint32_t>(connection.size()), error_.get(), renderer.handle());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_data_source_create_with_connection failed"));
  return converter_data_source(handle_);
}

inline dew_data_source_t converter_data_source::get() const
{
  dew_data_source_t return_ = dew_converter_data_source_get(_handle);
  return return_;
}

inline void converter_data_source::request_aabb(dew_converter_data_source_request_aabb_callback_t callback, void * callback_user_ptr) const
{
  dew_converter_data_source_request_aabb(_handle, callback, callback_user_ptr);
}

inline uint32_t converter_data_source::attribute_count() const
{
  uint32_t return_ = dew_converter_data_attribute_count(_handle);
  return return_;
}

inline std::string converter_data_source::get_attribute_name(int index) const
{
  return detail::out_string([&](char *buffer_, uint32_t capacity_) {
    return dew_converter_data_get_attribute_name(_handle, index, buffer_, capacity_);
  });
}

inline void converter_data_source::set_rendered_attribute(std::string_view name) const
{
  dew_converter_data_set_rendered_attribute(_handle, name.data(), static_cast<uint32_t>(name.size()));
}

inline void converter_data_source::set_viewport(int width, int height) const
{
  dew_converter_data_source_set_viewport(_handle, width, height);
}

inline void converter_data_source::set_pixel_error_threshold(double threshold) const
{
  dew_converter_data_source_set_pixel_error_threshold(_handle, threshold);
}

inline void converter_data_source::set_render_density_px(double density_px) const
{
  dew_converter_data_source_set_render_density_px(_handle, density_px);
}

inline void converter_data_source::set_gpu_memory_budget(size_t budget_bytes) const
{
  dew_converter_data_source_set_gpu_memory_budget(_handle, budget_bytes);
}

inline void converter_data_source::set_upload_budget_per_frame(size_t budget_bytes) const
{
  dew_converter_data_source_set_upload_budget_per_frame(_handle, budget_bytes);
}

inline void converter_data_source::set_max_in_flight_io(int max_requests) const
{
  dew_converter_data_source_set_max_in_flight_io(_handle, max_requests);
}

inline void converter_data_source::set_memory_budget(uint64_t total_bytes) const
{
  dew_converter_data_source_set_memory_budget(_handle, total_bytes);
}

inline uint64_t converter_data_source::get_memory_budget() const
{
  uint64_t return_ = dew_converter_data_source_get_memory_budget(_handle);
  return return_;
}

inline converter_data_source_get_memory_stats_result converter_data_source::get_memory_stats() const
{
  uint64_t heap_bytes_out{};
  uint64_t heap_max_out{};
  uint64_t budget_bytes_out{};
  uint64_t backlog_bytes_out{};
  uint64_t read_cache_bytes_out{};
  uint64_t resident_cpu_bytes_out{};
  uint32_t brake_level_out{};
  dew_converter_data_source_get_memory_stats(_handle, &heap_bytes_out, &heap_max_out, &budget_bytes_out, &backlog_bytes_out, &read_cache_bytes_out, &resident_cpu_bytes_out, &brake_level_out);
  return converter_data_source_get_memory_stats_result{heap_bytes_out, heap_max_out, budget_bytes_out, backlog_bytes_out, read_cache_bytes_out, resident_cpu_bytes_out, brake_level_out};
}

inline uint64_t converter_data_source::get_points_rendered() const
{
  uint64_t return_ = dew_converter_data_source_get_points_rendered(_handle);
  return return_;
}

inline uint8_t converter_data_source::is_animating() const
{
  uint8_t return_ = dew_converter_data_source_is_animating(_handle);
  return return_;
}

inline converter_data_source_get_frame_timings_result converter_data_source::get_frame_timings() const
{
  double tree_walk_ms_out{};
  double buffer_reconciliation_ms_out{};
  double gpu_upload_ms_out{};
  double refine_strategy_ms_out{};
  double frontier_scheduling_ms_out{};
  double draw_emission_ms_out{};
  double eviction_ms_out{};
  double total_ms_out{};
  int registry_node_count_out{};
  int active_set_size_out{};
  int nodes_drawn_out{};
  int transitioning_count_out{};
  int nodes_evicted_out{};
  int nodes_reconcile_destroyed_out{};
  int walker_node_count_out{};
  uint64_t walker_total_points_out{};
  int walker_trees_to_load_out{};
  int io_in_flight_out{};
  dew_converter_data_source_get_frame_timings(_handle, &tree_walk_ms_out, &buffer_reconciliation_ms_out, &gpu_upload_ms_out, &refine_strategy_ms_out, &frontier_scheduling_ms_out, &draw_emission_ms_out, &eviction_ms_out, &total_ms_out, &registry_node_count_out, &active_set_size_out, &nodes_drawn_out, &transitioning_count_out, &nodes_evicted_out, &nodes_reconcile_destroyed_out, &walker_node_count_out, &walker_total_points_out, &walker_trees_to_load_out, &io_in_flight_out);
  return converter_data_source_get_frame_timings_result{tree_walk_ms_out, buffer_reconciliation_ms_out, gpu_upload_ms_out, refine_strategy_ms_out, frontier_scheduling_ms_out, draw_emission_ms_out, eviction_ms_out, total_ms_out, registry_node_count_out, active_set_size_out, nodes_drawn_out, transitioning_count_out, nodes_evicted_out, nodes_reconcile_destroyed_out, walker_node_count_out, walker_total_points_out, walker_trees_to_load_out, io_in_flight_out};
}

inline void converter_data_source::set_debug_transitions(uint8_t enabled) const
{
  dew_converter_data_source_set_debug_transitions(_handle, enabled);
}

inline void converter_data_source::set_enable_virtual_subtrees(uint8_t enabled) const
{
  dew_converter_data_source_set_enable_virtual_subtrees(_handle, enabled);
}

inline uint8_t converter_data_source::get_enable_virtual_subtrees() const
{
  uint8_t return_ = dew_converter_data_source_get_enable_virtual_subtrees(_handle);
  return return_;
}

inline converter_data_source_get_virtual_stats_result converter_data_source::get_virtual_stats() const
{
  uint32_t promoted_out{};
  uint64_t gpu_bytes_out{};
  uint64_t resident_cpu_bytes_out{};
  uint32_t nodes_drawn_out{};
  dew_converter_data_source_get_virtual_stats(_handle, &promoted_out, &gpu_bytes_out, &resident_cpu_bytes_out, &nodes_drawn_out);
  return converter_data_source_get_virtual_stats_result{promoted_out, gpu_bytes_out, resident_cpu_bytes_out, nodes_drawn_out};
}

inline void converter_data_source::set_show_bounding_boxes(uint8_t enabled) const
{
  dew_converter_data_source_set_show_bounding_boxes(_handle, enabled);
}

inline dew_data_source_t converter_data_source::get_bbox_data_source() const
{
  dew_data_source_t return_ = dew_converter_data_source_get_bbox_data_source(_handle);
  return return_;
}

inline converter_data_source_get_tight_aabb_result converter_data_source::get_tight_aabb() const
{
  std::array<double, 3> min_out{};
  std::array<double, 3> max_out{};
  dew_converter_data_source_get_tight_aabb(_handle, min_out.data(), max_out.data());
  return converter_data_source_get_tight_aabb_result{min_out, max_out};
}

// ---- free functions ----

inline uint8_t access_can_block()
{
  uint8_t return_ = dew_access_can_block();
  return return_;
}

inline dew_converter_file_convert_callbacks_t laszip_callbacks()
{
  dew_converter_file_convert_callbacks_t return_ = dew_laszip_callbacks();
  return return_;
}

} // namespace dewpp
