/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dewfall's public C API as C++, in namespace `dewpp`. This header pulls in all of them; the
 * individual wrappers mirror the C layout, so <dew/access/query.hpp> is the C++ for
 * <dew/access/query.h> and can be included on its own.
 *
 * The C API is shaped for an ABI: opaque handles, out-parameters, caller-allocated dew_error_t **,
 * (pointer, length) string pairs, explicit destroy calls. This is the same API with the tedium
 * removed -- RAII handles, std::string_view in, std::string out, errors returned by value:
 *
 *     auto opened = dewpp::converter_t::create("out.dew", dew_open_file_semantics_truncate);
 *     if (!opened)
 *       return fail(opened.error().message());
 *     dewpp::converter_t conv = std::move(*opened);
 *     conv.add_data_file(files);
 *     conv.wait_idle();
 *
 * ERRORS, WITHOUT EXCEPTIONS. dewfall builds -fno-exceptions, so a failing constructor cannot report
 * by throwing -- which is why handles are created through static factories returning
 * `dewpp::result_t<T>` (std::expected<T, dewpp::error_t>). BEWARE: with exceptions disabled,
 * std::expected::value() on an error cannot throw and will abort instead. Check has_value(), or
 * dereference only once you have.
 *
 * OWNERSHIP. Owning handles are move-only and destroy on scope exit; `release()` hands the raw
 * handle back if you need to escape the wrapper. A few handles are BORROWED views the library owns
 * (attributes_t, buffer_t, to_render_t) -- those are copyable, destroy nothing, and are only valid
 * for as long as whatever handed them to you says they are.
 *
 * ALIASED, NOT REWRAPPED. Enums, value structs and constants are `using` aliases of the C types. A
 * parallel enum class would be a second source of truth that can drift, and conversions would buy
 * nothing. Callback structs and function pointers are likewise passed through as the C types,
 * because the C API's single void* user_ptr is the caller's to spend.
 */
#pragma once

#include <dew/access/query.hpp>
#include <dew/converter/converter.hpp>
#include <dew/converter/converter_data_source.hpp>
#include <dew/converter/laszip_file_convert_callbacks.hpp>
#include <dew/core/default_attribute_names.hpp>
#include <dew/core/error.hpp>
#include <dew/core/format.hpp>
#include <dew/core/pump.hpp>
#include <dew/core/types.hpp>
#include <dew/render/aabb.hpp>
#include <dew/render/aabb_data_source.hpp>
#include <dew/render/axis_gizmo_data_source.hpp>
#include <dew/render/buffer.hpp>
#include <dew/render/camera.hpp>
#include <dew/render/data_source.hpp>
#include <dew/render/draw_group.hpp>
#include <dew/render/environment_data_source.hpp>
#include <dew/render/flat_points_data_source.hpp>
#include <dew/render/origin_anchor_data_source.hpp>
#include <dew/render/renderer.hpp>
#include <dew/render/skybox_data_source.hpp>
