set(SDL2_INCLUDE_DIRECTORIES ${SDL2_INSTALL_DIR}/include;${SDL2_INSTALL_DIR}/include/SDL2)

if(WIN32)
  set(SDL2_IMPL_LIB_RELEASE ${SDL2_INSTALL_DIR}/lib/SDL2.lib)
  set(SDL2_IMPL_LIB_DEBUG ${SDL2_INSTALL_DIR}/lib/SDL2d.lib)

  set(SDL2_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/bin/SDL2.dll)
  set(SDL2_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/bin/SDL2d.dll)

  set(SDL2_MAIN_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/lib/SDL2main.lib)
  set(SDL2_MAIN_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/lib/SDL2maind.lib)
elseif(APPLE)
  set(SDL2_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/lib/libSDL2-2.0.dylib)
  set(SDL2_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/lib/libSDL2-2.0d.dylib)

  set(SDL2_MAIN_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/lib/libSDL2main.a)
  set(SDL2_MAIN_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/lib/libSDL2maind.a)
else()
  set(SDL2_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/bin/SDL2.dll)
  set(SDL2_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/bin/SDL2d.dll)

  set(SDL2_MAIN_LOCATION_RELEASE ${SDL2_INSTALL_DIR}/lib/SDL2main.lib)
  set(SDL2_MAIN_LOCATION_DEBUG ${SDL2_INSTALL_DIR}/lib/SDL2maind.lib)

endif()

if (NOT TARGET SDL2::SDL2)
  add_library(SDL2::SDL2 SHARED IMPORTED)
  set_target_properties(SDL2::SDL2
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET sdl_build
    CMDEP_INCLUDE_DIRS      "${SDL2_INCLUDE_DIRECTORIES}"
    CMDEP_IMPLIB_RELEASE            "${SDL2_IMPL_LIB_RELEASE}"
    CMDEP_IMPLIB_DEBUG              "${SDL2_IMPL_LIB_DEBUG}"
    CMDEP_LOCATION_RELEASE          "${SDL2_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${SDL2_LOCATION_DEBUG}"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()

if (NOT TARGET SDL2::SDL2main)
  add_library(SDL2::SDL2main STATIC IMPORTED)
  set_target_properties(SDL2::SDL2main
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET sdl_build
    CMDEP_INCLUDE_DIRS      "${SDL2_INCLUDE_DIRECTORIES}"
    CMDEP_LOCATION_RELEASE          "${SDL2_MAIN_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${SDL2_MAIN_LOCATION_DEBUG}"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()
