/* GENERATED by tools/bindgen/generate_cpp_await.py -- do not edit.
 *
 * dew/access/query_async.hpp -- co_await for the pump-driven handles declared in <dew/access/query.h>.
 *
 * A sibling of the sync wrapper next door: anything driven by the pump is an async candidate, and
 * `//= awaitable:` on the handle is what marks one. The driver lives in <dew/core/pump_async.hpp>.
 *
 *     if (co_await dewpp::async::ready(driver, dataset) != dew_dataset_ready)
 *       co_return 1;
 *
 * Resumes with the handle's terminal value, so the caller still distinguishes success from failure.
 */
#pragma once

#include <dew/core/pump_async.hpp>
#include <dew/access/query.h>
#include <dew/access/query.hpp>

namespace dewpp::async
{

// Dataset: await until dew_dataset_state() stops reporting dew_dataset_opening.
//
// Resumes with the terminal value, so the caller still has to distinguish success from failure.
// Returns immediately if the handle is already terminal, and if it is null -- a null handle can
// never make progress, so awaiting one would hang rather than fail.
[[nodiscard]] inline auto ready(driver_t &driver, dew_dataset_t *handle)
{
  struct awaiter_t
  {
    driver_t &driver;
    dew_dataset_t *handle;

    [[nodiscard]] bool done() const { return !handle || dew_dataset_state(handle) != dew_dataset_opening; }
    [[nodiscard]] bool await_ready() const { return done(); }
    void await_suspend(std::coroutine_handle<> continuation)
    {
      auto *h = handle;
      driver.await_register([h]() { return !h || dew_dataset_state(h) != dew_dataset_opening; }, continuation);
    }
    [[nodiscard]] auto await_resume() const { return dew_dataset_state(handle); }
  };
  return awaiter_t{driver, handle};
}

// The same, for the owning wrapper next door -- so a dewpp caller need not reach for .handle().
[[nodiscard]] inline auto ready(driver_t &driver, const dewpp::dataset_t &handle)
{
  return ready(driver, handle.handle());
}

// Request: await until dew_request_status() stops reporting dew_request_pending.
//
// Resumes with the terminal value, so the caller still has to distinguish success from failure.
// Returns immediately if the handle is already terminal, and if it is null -- a null handle can
// never make progress, so awaiting one would hang rather than fail.
[[nodiscard]] inline auto ready(driver_t &driver, dew_request_t *handle)
{
  struct awaiter_t
  {
    driver_t &driver;
    dew_request_t *handle;

    [[nodiscard]] bool done() const { return !handle || dew_request_status(handle) != dew_request_pending; }
    [[nodiscard]] bool await_ready() const { return done(); }
    void await_suspend(std::coroutine_handle<> continuation)
    {
      auto *h = handle;
      driver.await_register([h]() { return !h || dew_request_status(h) != dew_request_pending; }, continuation);
    }
    [[nodiscard]] auto await_resume() const { return dew_request_status(handle); }
  };
  return awaiter_t{driver, handle};
}

// The same, for the owning wrapper next door -- so a dewpp caller need not reach for .handle().
[[nodiscard]] inline auto ready(driver_t &driver, const dewpp::request_t &handle)
{
  return ready(driver, handle.handle());
}

} // namespace dewpp::async
