/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/access/query.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/access/query.h>
#include <dew/core/error.hpp>
#include <dew/core/pump.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using dataset_state_t = dew_dataset_state_t;
using request_status_t = dew_request_status_t;
using lod_mode_t = dew_lod_mode_t;
using clip_mode_t = dew_clip_mode_t;
using position_format_t = dew_position_format_t;
using dataset_options_t = dew_dataset_options_t;
using dataset_info_t = dew_dataset_info_t;
using region_request_t = dew_region_request_t;
using attribute_buffer_t = dew_attribute_buffer_t;
using result_node_t = dew_result_node_t;
using request_result_t = dew_request_result_t;

class dataset_t;
class request_t;

//  Awaiting these two.
//
//  The whole protocol is one line each: keep looking until poll(handle) != pending. dew_dataset_t is
//  `opening` until the index read lands; dew_request_t is `pending` until the query finishes. The pump
//  guarantees a wake when either changes, so a poll after that wake is a pure read -- no completion
//  callback has to outlive the handle, and nothing has to be retracted when a caller loses interest.
//
//  tools/bindgen turns these into await wrappers: dew/await/dew_await.hpp for C++ coroutines and
//  dew.aio for Python. Adding an awaitable handle is this annotation and nothing else.
//  Both handles are OWNED -- the wrappers must destroy them -- but neither destructor is named
//  *_destroy, which is the only thing the generators infer from. So say it: without this a generated
//  wrapper treats them as borrowed views and quietly leaks every dataset and every request.
// Owns its dew_dataset_t: move-only, destroyed with dew_dataset_close.
class dataset_t
{
public:
  dataset_t() = default;
  explicit dataset_t(dew_dataset_t *handle)
    : _handle(handle)
  {
  }

  ~dataset_t() { reset(); }
  dataset_t(dataset_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  dataset_t &operator=(dataset_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  dataset_t(const dataset_t &) = delete;
  dataset_t &operator=(const dataset_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_dataset_close(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_dataset_t *release()
  {
    dew_dataset_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_dataset_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  //  Returns immediately with the dataset in `opening`; `error` is only set for arguments that cannot
  //  be used at all. A missing or corrupt dataset surfaces as state == dew_dataset_error, so that the
  //  failure path is the same on native and under wasm, where opening cannot block.
  //
  //  `pump` is where completions are delivered. Pass one to drive several subsystems from a single
  //  wake, or NULL to have the dataset own a private pump -- in which case dew_dataset_poll drives it
  //  and you need not know the pump exists.
  static result_t<dataset_t> create(std::string_view url, std::string_view connection, const dew_dataset_options_t & options, const pump_t & pump);

  dew_dataset_state_t state() const;

  std::optional<error_t> get_error() const;

  //  Dispatch this dataset's completions on the calling thread; returns how many were dispatched.
  //
  //  Only valid on a dataset with a PRIVATE pump (created with pump == NULL). On a dataset sharing a
  //  pump it returns 0 -- draining one subsystem of a shared pump is exactly the partial drain that
  //  loses wakeups, so call dew_pump_poll instead.
  uint32_t poll() const;

  uint32_t pending_count() const;

  dew_dataset_state_t wait_ready(int32_t timeout_ms) const;

  dew_dataset_info_t get_info() const;

  uint32_t attribute_count() const;

  std::string get_attribute_name(uint32_t index) const;

private:
  dew_dataset_t *_handle = nullptr;
};

// Owns its dew_request_t: move-only, destroyed with dew_request_release.
class request_t
{
public:
  request_t() = default;
  explicit request_t(dew_request_t *handle)
    : _handle(handle)
  {
  }

  ~request_t() { reset(); }
  request_t(request_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  request_t &operator=(request_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  request_t(const request_t &) = delete;
  request_t &operator=(const request_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_request_release(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_request_t *release()
  {
    dew_request_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_request_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  dew_request_status_t status() const;

  dew_request_status_t wait(int32_t timeout_ms) const;

  void cancel() const;

  std::optional<error_t> get_error() const;

  float completion_factor() const;

  std::optional<dew_request_result_t> get_result() const;

  uint64_t attribute_size(uint32_t attribute_index) const;

  // Not wrapped -- call the C function directly with get():
  //   dew_request_copy_attribute

private:
  dew_request_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<dataset_t> dataset_t::create(std::string_view url, std::string_view connection, const dew_dataset_options_t & options, const pump_t & pump)
{
  detail::error_out_t error_;
  dew_dataset_t *handle_ = dew_dataset_create(url.data(), static_cast<uint32_t>(url.size()), connection.data(), static_cast<uint32_t>(connection.size()), &options, pump.handle(), error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_dataset_create failed"));
  return dataset_t(handle_);
}

inline dew_dataset_state_t dataset_t::state() const
{
  dew_dataset_state_t return_ = dew_dataset_state(_handle);
  return return_;
}

inline std::optional<error_t> dataset_t::get_error() const
{
  detail::error_out_t error_;
  dew_dataset_get_error(_handle, error_.slot());
  return error_.take_if_set();
}

inline uint32_t dataset_t::poll() const
{
  uint32_t return_ = dew_dataset_poll(_handle);
  return return_;
}

inline uint32_t dataset_t::pending_count() const
{
  uint32_t return_ = dew_dataset_pending_count(_handle);
  return return_;
}

inline dew_dataset_state_t dataset_t::wait_ready(int32_t timeout_ms) const
{
  dew_dataset_state_t return_ = dew_dataset_wait_ready(_handle, timeout_ms);
  return return_;
}

inline dew_dataset_info_t dataset_t::get_info() const
{
  dew_dataset_info_t info_out{};
  dew_dataset_get_info(_handle, &info_out);
  return info_out;
}

inline uint32_t dataset_t::attribute_count() const
{
  uint32_t return_ = dew_dataset_attribute_count(_handle);
  return return_;
}

inline std::string dataset_t::get_attribute_name(uint32_t index) const
{
  return detail::out_string([&](char *buffer_, uint32_t capacity_) {
    return dew_dataset_get_attribute_name(_handle, index, buffer_, capacity_);
  });
}

inline dew_request_status_t request_t::status() const
{
  dew_request_status_t return_ = dew_request_status(_handle);
  return return_;
}

inline dew_request_status_t request_t::wait(int32_t timeout_ms) const
{
  dew_request_status_t return_ = dew_request_wait(_handle, timeout_ms);
  return return_;
}

inline void request_t::cancel() const
{
  dew_request_cancel(_handle);
}

inline std::optional<error_t> request_t::get_error() const
{
  detail::error_out_t error_;
  dew_request_get_error(_handle, error_.slot());
  return error_.take_if_set();
}

inline float request_t::completion_factor() const
{
  float return_ = dew_request_completion_factor(_handle);
  return return_;
}

inline std::optional<dew_request_result_t> request_t::get_result() const
{
  dew_request_result_t out_out{};
  bool ok_ = dew_request_get_result(_handle, &out_out);
  return ok_ ? std::optional<dew_request_result_t>(out_out) : std::nullopt;
}

inline uint64_t request_t::attribute_size(uint32_t attribute_index) const
{
  uint64_t return_ = dew_request_attribute_size(_handle, attribute_index);
  return return_;
}

inline uint8_t access_can_block()
{
  uint8_t return_ = dew_access_can_block();
  return return_;
}

} // namespace dewpp
