set(LASZIP_API_INCLUDE_DIRECTORIES "${LASZIP_INSTALL_DIR}/include;${LASZIP_INSTALL_DIR}/include/laszip")

if (WIN32)
  set(LASZIP_API_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/laszip_api.lib)
  set(LASZIP_API_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/laszip_api.lib)
  set(LASZIP_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/laszip.lib)
  set(LASZIP_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/laszip.lib)
else()
  set(LASZIP_API_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/liblaszip_api.a)
  set(LASZIP_API_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/liblaszip_api.a)
  set(LASZIP_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/liblaszip.a)
  set(LASZIP_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/liblaszip.a)
endif()

if (NOT TARGET laszip::api)
  add_library(laszip::api STATIC IMPORTED)
  set_target_properties(laszip::api
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET laszip_build
    CMDEP_INCLUDE_DIRS      "${LASZIP_API_INCLUDE_DIRECTORIES}"
    CMDEP_LOCATION_RELEASE          "${LASZIP_API_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${LASZIP_API_LOCATION_DEBUG}"
    CMDEP_SUB_TARGETS         "laszip::impl"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()

if (NOT TARGET laszip::impl)
  add_library(laszip::impl STATIC IMPORTED)
  set_target_properties(laszip::impl
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET laszip_build
    CMDEP_INCLUDE_DIRS      "${LASZIP_API_INCLUDE_DIRECTORIES}"
    CMDEP_LOCATION_RELEASE          "${LASZIP_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${LASZIP_LOCATION_DEBUG}"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()
