set(LASZIP_API_INCLUDE_DIRECTORIES "${LASZIP_INSTALL_DIR}/include;${LASZIP_INSTALL_DIR}/include/laszip")

if (WIN32)
  set(LASZIP_API_IMPLIB_RELEASE ${LASZIP_INSTALL_DIR}/lib/laszip_api3.lib)
  set(LASZIP_API_IMPLIB_DEBUG ${LASZIP_INSTALL_DIR}/lib/laszip_api3d.lib)
  set(LASZIP_IMPL_IMPLIB_RELEASE ${LASZIP_INSTALL_DIR}/lib/laszip3.lib)
  set(LASZIP_IMPL_IMPLIB_DEBUG ${LASZIP_INSTALL_DIR}/lib/laszip3d.lib)

  set(LASZIP_API_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/bin/laszip_api3.dll)
  set(LASZIP_API_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/bin/laszip_api3d.dll)
  set(LASZIP_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/bin/laszip3.dll)
  set(LASZIP_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/bin/laszip3d.dll)

elseif(APPLE)
  set(LASZIP_API_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/liblaszip_api.8.dylib)
  set(LASZIP_API_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/liblaszip_api.8.dylib)
  set(LASZIP_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/lib/liblaszip.dylib)
  set(LASZIP_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/lib/liblaszip.dylib)
else()
  set(LASZIP_API_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/bin/laszip_api3.dll)
  set(LASZIP_API_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/bin/laszip_api3d.dll)
  set(LASZIP_LOCATION_RELEASE ${LASZIP_INSTALL_DIR}/bin/laszip3.dll)
  set(LASZIP_LOCATION_DEBUG ${LASZIP_INSTALL_DIR}/bin/laszip3d.dll)
endif()

if (NOT TARGET laszip::api)
  add_library(laszip::api SHARED IMPORTED)
  set_target_properties(laszip::api
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET laszip_build
    CMDEP_INCLUDE_DIRS      "${LASZIP_API_INCLUDE_DIRECTORIES}"
    CMDEP_COMPILE_DEFS      "LASZIP_DYN_LINK=1"
    CMDEP_IMPLIB_RELEASE            "${LASZIP_API_IMPLIB_RELEASE}"
    CMDEP_IMPLIB_DEBUG              "${LASZIP_API_IMPLIB_DEBUG}"
    CMDEP_LOCATION_RELEASE          "${LASZIP_API_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${LASZIP_API_LOCATION_DEBUG}"
    CMDEP_SUB_TARGETS         "laszip::impl"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()

if (NOT TARGET laszip::impl)
  add_library(laszip::impl SHARED IMPORTED)
  set_target_properties(laszip::impl
    PROPERTIES
    CMDEP_EXTERNAL "On"
    CMDEP_TARGET laszip_build
    CMDEP_INCLUDE_DIRS      "${LASZIP_API_INCLUDE_DIRECTORIES}"
    CMDEP_COMPILE_DEFS      "LASZIP_DYN_LINK=1"
    CMDEP_IMPLIB_RELEASE            "${LASZIP_IMPL_IMPLIB_RELEASE}"
    CMDEP_IMPLIB_DEBUG              "${LASZIP_IMPL_IMPLIB_DEBUG}"
    CMDEP_LOCATION_RELEASE          "${LASZIP_LOCATION_RELEASE}"
    CMDEP_LOCATION_DEBUG            "${LASZIP_LOCATION_DEBUG}"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()
