#!/usr/bin/env python3
"""Generate the header-only C++ await wrappers from the `//= awaitable:` annotations.

dewfall's C API never calls user code on its own threads. It signals -- one wake per burst -- and the
host dispatches with dew_pump_poll on whatever thread it likes. That is the right contract for a C
API and the wrong shape to write against, so this emits the adapter:

    VIO_MAIN(loop, argc, argv)
    {
      dewpp::async::driver_t driver(loop);
      auto *ds = dew_dataset_create(url, len, nullptr, 0, nullptr, driver.pump(), &error);
      if (co_await dewpp::async::ready(driver, ds) != dew_dataset_ready) co_return 1;
      auto *req = dew_dataset_request_region(ds, &spec, &error);
      if (co_await dewpp::async::ready(driver, req) == dew_request_completed) { ... }
    }

LAYOUT. Anything driven by the pump is an async candidate, and `//= awaitable:` is what marks one. So
the wrappers are emitted as SIBLINGS of the sync ones: the awaitable handles declared in
`dew/access/query.h` get `dew/access/query_async.hpp`, next to `dew/access/query.hpp`. The driver
itself lives in `dew/core/pump_async.hpp`, beside the pump it drives. `_async` is the one part of the
tree that needs vio, which is exactly why it is separable -- a caller that has no event loop includes
the sync headers and never pays for it.

Two halves:

  * the DRIVER is fixed text below. It is the same code whatever the API contains -- pump wiring,
    wake -> loop hop, and the waiter list -- so generating it from the IR would be pretending.
  * the per-handle `ready()` overloads come from the annotations. Adding an awaitable handle is one
    `//= awaitable:` line and nothing else, which is the point of doing this in the generator rather
    than by hand.

Usage:
    generate_cpp_await.py --api dew_api.json --output src/access/dew/access/query_async.hpp
"""

import argparse
import json
import pathlib
import re
import sys

BANNER = """/* GENERATED by tools/bindgen/generate_cpp_await.py -- do not edit.
 *
 * @HEADER@ -- co_await for the pump-driven handles declared in @C_HEADER@.
 *
 * A sibling of the sync wrapper next door: anything driven by the pump is an async candidate, and
 * `//= awaitable:` on the handle is what marks one. The driver lives in <dew/core/pump_async.hpp>.
 *
 *     if (co_await dewpp::async::ready(driver, dataset) != dew_dataset_ready)
 *       co_return 1;
 *
 * Resumes with the handle's terminal value, so the caller still distinguishes success from failure.
 */
#pragma once

"""

DRIVER_BANNER = """/* GENERATED by tools/bindgen/generate_cpp_await.py -- do not edit.
 *
 * dew/core/pump_async.hpp -- the pump, driven from a vio event loop, as coroutines.
 *
 * dewfall never calls user code on its own threads: it raises ONE wake per burst of completions, and
 * the host dispatches them with dew_pump_poll on a thread of its choosing. This is that handshake:
 *
 *     #include <dew/access/query_async.hpp>
 *     #include <vio/run.h>
 *
 *     VIO_MAIN(loop, argc, argv)
 *     {
 *       dewpp::async::driver_t driver(loop);
 *       dew_error_t *error = nullptr;
 *       auto *dataset = dew_dataset_create(url, len, nullptr, 0, nullptr, driver.pump(), &error);
 *       if (co_await dewpp::async::ready(driver, dataset) != dew_dataset_ready)
 *         co_return 1;
 *       ...
 *     }
 *
 * Header-only and inline: include it, link the public C API, bring your own vio loop. This is the one
 * part of the C++ wrapper that needs vio, which is why it is a separate file -- a caller with no
 * event loop includes the sync headers and never pays for it.
 *
 * THREADING. The wake fires on an arbitrary internal thread -- and under wasm possibly re-entrantly,
 * because there the loop is cooperative rather than a separate thread. It may therefore only SIGNAL,
 * which is exactly what it does: post to the loop and return. Everything else (dew_pump_poll, the
 * waiter list, resuming coroutines) happens on the loop thread, which is what makes the awaiters free
 * of locks. Await only from coroutines running on the driver's own loop.
 */
#pragma once

#include <dew/core/pump.h>

#include <vio/event_loop.h>

#include <coroutine>
#include <functional>
#include <utility>
#include <vector>

"""


DRIVER = '''namespace dewpp::async
{

// Owns the pump/loop wiring. One driver drives any number of datasets and requests: the pump is
// shared, which is what it is for -- a single wake, and a single poll that drains everything.
class driver_t
{
public:
  // Creates and owns a pump.
  explicit driver_t(vio::event_loop_t &loop)
    : _loop(loop)
    , _pump(dew_pump_create())
    , _owns_pump(true)
  {
    dew_pump_set_wake_callback(_pump, &driver_t::on_wake, this);
  }

  // Borrows an existing pump, for a host that already has one.
  driver_t(vio::event_loop_t &loop, dew_pump_t *pump)
    : _loop(loop)
    , _pump(pump)
    , _owns_pump(false)
  {
    dew_pump_set_wake_callback(_pump, &driver_t::on_wake, this);
  }

  ~driver_t()
  {
    // Detach BEFORE anything else: passing null waits out a wake that is already in flight, so a late
    // completion cannot post into a half-destroyed driver.
    dew_pump_set_wake_callback(_pump, nullptr, nullptr);
    if (_owns_pump)
      dew_pump_destroy(_pump);
  }

  driver_t(const driver_t &) = delete;
  driver_t &operator=(const driver_t &) = delete;

  // Pass this to dew_dataset_create. Note that dew_dataset_poll returns 0 on a dataset sharing a
  // pump -- draining one subsystem of a shared pump is the partial drain that loses wakeups. Poll the
  // pump, which is what drain() does.
  [[nodiscard]] dew_pump_t *pump() const { return _pump; }
  [[nodiscard]] vio::event_loop_t &event_loop() const { return _loop; }

  // Dispatch, then resume whatever became ready. Public because a host with its own frame loop (a
  // renderer, say) may prefer to drive it from there rather than wait to be woken.
  void drain()
  {
    dew_pump_poll(_pump);
    // Resume from a snapshot: a resumed coroutine runs to its next suspension immediately and may
    // register a new waiter, which would invalidate an iterator over the live vector.
    std::vector<std::coroutine_handle<>> ready;
    for (size_t i = 0; i < _waiters.size();)
    {
      if (_waiters[i].predicate())
      {
        ready.push_back(_waiters[i].continuation);
        _waiters[i] = std::move(_waiters.back());
        _waiters.pop_back();
      }
      else
      {
        ++i;
      }
    }
    for (auto continuation : ready)
      continuation.resume();
  }

  // co_await until `predicate` holds. The generated ready() overloads below are thin wrappers around
  // this; use it directly for a condition the annotations do not describe.
  class awaiter_t
  {
  public:
    awaiter_t(driver_t &driver, std::function<bool()> predicate)
      : _driver(driver)
      , _predicate(std::move(predicate))
    {
    }

    bool await_ready() const { return _predicate(); }

    void await_suspend(std::coroutine_handle<> continuation) { _driver._waiters.push_back({_predicate, continuation}); }

    void await_resume() const {}

  private:
    driver_t &_driver;
    std::function<bool()> _predicate;
  };

  awaiter_t until(std::function<bool()> predicate) { return awaiter_t(*this, std::move(predicate)); }

  // The seam the generated awaiters use to park themselves. Loop thread only, like everything else
  // here: a coroutine awaiting from another thread would race drain().
  void await_register(std::function<bool()> predicate, std::coroutine_handle<> continuation) { _waiters.push_back({std::move(predicate), continuation}); }

private:
  static void on_wake(void *user_ptr)
  {
    // ARBITRARY THREAD, possibly re-entrant under wasm. Post and return -- that is the entire legal
    // vocabulary here. run_in_loop is thread-safe, which is what makes this sound.
    auto *self = static_cast<driver_t *>(user_ptr);
    self->_loop.run_in_loop([self]() { self->drain(); });
  }

  struct waiter_t
  {
    std::function<bool()> predicate;
    std::coroutine_handle<> continuation;
  };

  vio::event_loop_t &_loop;
  dew_pump_t *_pump;
  bool _owns_pump;
  std::vector<waiter_t> _waiters;
};

'''

EPILOGUE = '''} // namespace dewpp::async
'''


def wrapper_name(bound_name):
    """`ConverterDataSource` -> `converter_data_source_t`; must match generate_cpp.type_name()."""
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", bound_name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower() + "_t"


def emit_awaitable(cls):
    """One `ready()` overload per annotated handle, plus a release helper when it has one."""
    spec = cls["awaitable"]
    handle = cls["handle_type"]
    wrapper = f"dewpp::{wrapper_name(cls['bound_name'])}"
    poll = spec["poll"]
    pending = spec["pending"]
    lines = []
    lines.append(f"// {cls['bound_name']}: await until {poll}() stops reporting {pending}.")
    lines.append(f"//")
    lines.append(f"// Resumes with the terminal value, so the caller still has to distinguish success from failure.")
    lines.append(f"// Returns immediately if the handle is already terminal, and if it is null -- a null handle can")
    lines.append(f"// never make progress, so awaiting one would hang rather than fail.")
    lines.append(f"[[nodiscard]] inline auto ready(driver_t &driver, {handle} *handle)")
    lines.append("{")
    lines.append("  struct awaiter_t")
    lines.append("  {")
    lines.append("    driver_t &driver;")
    lines.append(f"    {handle} *handle;")
    lines.append("")
    lines.append(f"    [[nodiscard]] bool done() const {{ return !handle || {poll}(handle) != {pending}; }}")
    lines.append("    [[nodiscard]] bool await_ready() const { return done(); }")
    lines.append("    void await_suspend(std::coroutine_handle<> continuation)")
    lines.append("    {")
    lines.append("      auto *h = handle;")
    lines.append(f"      driver.await_register([h]() {{ return !h || {poll}(h) != {pending}; }}, continuation);")
    lines.append("    }")
    lines.append(f"    [[nodiscard]] auto await_resume() const {{ return {poll}(handle); }}")
    lines.append("  };")
    lines.append("  return awaiter_t{driver, handle};")
    lines.append("}")
    lines.append("")
    lines.append(f"// The same, for the owning wrapper next door -- so a dewpp caller need not reach for .handle().")
    lines.append(f"[[nodiscard]] inline auto ready(driver_t &driver, const {wrapper} &handle)")
    lines.append("{")
    lines.append("  return ready(driver, handle.handle());")
    lines.append("}")
    # No release guard here: the sync wrapper (dewpp::request_t) already owns the handle and destroys
    # it, which is what the `//= destroy:` annotation is for. A second RAII type would be a second
    # owner.
    return "\n".join(lines)


DRIVER_HEADER = "dew/core/pump_async.hpp"


def async_header(c_header):
    """`dew/access/query.h` -> `dew/access/query_async.hpp`."""
    return c_header[:-2] + "_async.hpp" if c_header.endswith(".h") else c_header + "_async.hpp"


def sync_header(c_header):
    return c_header[:-2] + ".hpp" if c_header.endswith(".h") else c_header + ".hpp"


def generate_files(api):
    semantic = api["semantic"] if "semantic" in api else api
    classes = [c for c in semantic["classes"] if c.get("awaitable")]
    if not classes:
        raise SystemExit("no //= awaitable: handles found -- nothing to generate")

    files = {DRIVER_HEADER: DRIVER_BANNER + DRIVER + EPILOGUE}

    by_header = {}
    for cls in classes:
        by_header.setdefault(cls["header"], []).append(cls)

    for c_header, entries in sorted(by_header.items()):
        relative = async_header(c_header)
        parts = [BANNER.replace("@HEADER@", relative).replace("@C_HEADER@", f"<{c_header}>")]
        parts.append(f"#include <{DRIVER_HEADER}>\n")
        parts.append(f"#include <{c_header}>\n")
        # The sync wrapper too, so ready() can also take a dewpp handle rather than a raw pointer.
        parts.append(f"#include <{sync_header(c_header)}>\n\n")
        parts.append("namespace dewpp::async\n{\n\n")
        for cls in entries:
            parts.append(emit_awaitable(cls))
            parts.append("\n\n")
        parts.append(EPILOGUE)
        files[relative] = "".join(parts)

    return files


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--api", required=True, help="dew_api.json from parse_headers.py")
    parser.add_argument("--output-dir", required=True, help="root the dew/ tree is written under")
    parser.add_argument("--check", action="store_true", help="fail if the tree is not what would be generated")
    args = parser.parse_args(argv)

    with open(args.api, "r", encoding="utf-8") as handle:
        api = json.load(handle)
    files = generate_files(api)
    root = pathlib.Path(args.output_dir)

    if args.check:
        stale = [relative for relative, text in sorted(files.items()) if not (root / relative).exists() or (root / relative).read_text() != text]
        if stale:
            for relative in stale:
                print(f"cpp-await: {relative} is stale -- rerun generate_cpp_await.py", file=sys.stderr)
            return 1
        print(f"cpp-await: {len(files)} headers up to date")
        return 0

    for relative, text in sorted(files.items()):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"cpp-await: {len(files)} headers ({', '.join(sorted(files))})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
