#!/usr/bin/env python3
"""Generate the header-only C++ wrapper for the whole public C API, in namespace `dewpp`.

The C API is what it has to be: opaque handles, out-parameters, caller-allocated `dew_error_t **`,
`(pointer, length)` string pairs, explicit destroy calls. That is right for an ABI and tedious to
write against, so this emits the C++ a caller actually wants -- RAII handles, `std::string_view` in,
`std::string` out, and errors returned by value -- from the same IR the Python bindings come from.
One description of the API, several wrappers, no hand-maintained duplicate.

    dewpp::converter_t conv = *dewpp::converter_t::create("out.dew", dew_open_file_semantics_truncate);
    conv.add_data_file(files);
    conv.wait_idle();

WHY std::expected AND NOT EXCEPTIONS. The project builds -fno-exceptions, so a failing constructor
cannot report by throwing. Every fallible call therefore returns `dewpp::result<T>` (an alias for
std::expected<T, dewpp::error>), and handle construction is a static factory rather than a
constructor. Note this means `.value()` must not be called on an error -- with -fno-exceptions it
cannot throw and will abort. Check `has_value()`, or dereference only after checking.

WHAT IS DELIBERATELY NOT WRAPPED. Enums, value structs and constants are ALIASED, not re-declared: a
parallel `enum class` would be a second source of truth that can drift from the C one, and the
conversion would buy nothing. Callback structs and function pointers are passed through as the C
types, because a std::function trampoline needs somewhere to live and the C API's single `void *`
user_ptr slot is already the caller's -- wrapping it would either leak or silently limit them to one
registration. That is a deliberate floor, not an oversight.

Usage:
    generate_cpp.py --api dew_api.json --output bindings/cpp/dew/dewpp.hpp [--check]
"""

import argparse
import json
import re
import sys

# C++ keywords a bound_name could collide with.
_RESERVED = {
    "alignas", "alignof", "and", "asm", "auto", "bool", "break", "case", "catch", "char", "class",
    "const", "continue", "default", "delete", "do", "double", "else", "enum", "explicit", "export",
    "extern", "false", "float", "for", "friend", "goto", "if", "inline", "int", "long", "mutable",
    "namespace", "new", "not", "operator", "or", "private", "protected", "public", "register",
    "return", "short", "signed", "sizeof", "static", "struct", "switch", "template", "this", "throw",
    "true", "try", "typedef", "typename", "union", "unsigned", "using", "virtual", "void", "while",
    "xor",
}


class EmitError(Exception):
    pass


def san(name):
    return name + "_" if name in _RESERVED else name


def snake(camel):
    """`ConverterDataSource` -> `converter_data_source`."""
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", camel)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


PROLOGUE = '''/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * A header-only C++ wrapper for dewfall's public C API, in namespace `dewpp`.
 *
 * The C API is shaped for an ABI: opaque handles, out-parameters, caller-allocated dew_error_t **,
 * (pointer, length) string pairs, explicit destroy calls. This is the same API with the tedium
 * removed -- RAII handles, std::string_view in, std::string out, errors returned by value:
 *
 *     auto opened = dewpp::converter::create("out.dew", dew_open_file_semantics_truncate);
 *     if (!opened)
 *       return fail(opened.error().message());
 *     dewpp::converter conv = std::move(*opened);
 *     conv.add_data_file(files);
 *     conv.wait_idle();
 *
 * ERRORS, WITHOUT EXCEPTIONS. dewfall builds -fno-exceptions, so a failing constructor cannot report
 * by throwing -- which is why handles are created through static factories returning
 * `dewpp::result<T>` (std::expected<T, dewpp::error>). BEWARE: with exceptions disabled,
 * std::expected::value() on an error cannot throw and will abort instead. Check has_value(), or
 * dereference only once you have.
 *
 * OWNERSHIP. Owning handles are move-only and destroy on scope exit; `release()` hands the raw
 * handle back if you need to escape the wrapper. A few handles are BORROWED views the library owns
 * (attributes, buffer, to_render) -- those are copyable, destroy nothing, and are only valid for as
 * long as whatever handed them to you says they are.
 *
 * ALIASED, NOT REWRAPPED. Enums, value structs and constants are `using` aliases of the C types. A
 * parallel enum class would be a second source of truth that can drift, and conversions would buy
 * nothing. Callback structs and function pointers are likewise passed through as the C types,
 * because the C API's single void* user_ptr is the caller's to spend.
 */
#pragma once

'''

STD_INCLUDES = '''
#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

'''

ERROR_TYPE = '''namespace dewpp
{

// A VALUE, not a handle.
//
// dew_error_get_info hands back a const char * owned by the dew_error_t, so anything that outlives
// the handle has to copy. Owning the handle instead would work but makes the error move-only, which
// is a poor payload for std::expected. Copy once, at the boundary, and be done.
//
// dew_error_t itself therefore gets no wrapper class here -- it would only ever be a detail of this.
class error
{
public:
  error() = default;
  error(int code, std::string message)
    : _code(code)
    , _message(std::move(message))
  {
  }

  [[nodiscard]] int code() const { return _code; }
  [[nodiscard]] const std::string &message() const { return _message; }
  [[nodiscard]] explicit operator bool() const { return _code != 0 || !_message.empty(); }

private:
  int _code = 0;
  std::string _message;
};

// The return type of anything that can fail. Note again: with -fno-exceptions, .value() on an error
// aborts rather than throwing -- check has_value() first.
template <class T> using result = std::expected<T, error>;
// For a fallible call with nothing to return.
using status = std::expected<void, error>;

namespace detail
{
// Copy a dew_error_t into a value. A null handle, or one nobody set, becomes `fallback` -- the C API
// has calls that fail without writing an error, and silently returning a blank one would be worse.
inline error read_error(const dew_error_t *handle, const char *fallback)
{
  if (!handle)
    return error(-1, fallback);
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return error(-1, fallback);
  return error(code, std::string(text ? text : "", length));
}

// For an ACCESSOR: is there actually an error in there?
//
// Not the same question as "was a handle written". dew_dataset_get_error / dew_request_get_error go
// through fill_error, which ALWAYS allocates -- it copies the stored error even when that error is
// blank. So a non-null handle proves nothing and only the content can answer.
inline std::optional<error> read_error_or_none(const dew_error_t *handle)
{
  if (!handle)
    return std::nullopt;
  int code = 0;
  const char *text = nullptr;
  size_t length = 0;
  dew_error_get_info(handle, &code, &text, &length);
  if (code == 0 && length == 0)
    return std::nullopt;
  return error(code, std::string(text ? text : "", length));
}

// The dew_error_t ** convention: the callee allocates, the caller destroys.
class error_out
{
public:
  error_out() = default;
  ~error_out()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  error_out(const error_out &) = delete;
  error_out &operator=(const error_out &) = delete;

  [[nodiscard]] dew_error_t **slot() { return &_handle; }
  [[nodiscard]] bool set() const { return _handle != nullptr; }
  [[nodiscard]] error take(const char *fallback) const { return read_error(_handle, fallback); }
  // For accessors, where a written handle does not mean a real error.
  [[nodiscard]] std::optional<error> take_if_set() const { return read_error_or_none(_handle); }

private:
  dew_error_t *_handle = nullptr;
};

// The dew_error_t * convention: the CALLER allocates, so the object always exists and its existence
// says nothing. "Did it fail" is `code != 0 || length != 0` -- an untouched dew_error_create() has
// code 0 and an empty (but non-null) message.
class scoped_error
{
public:
  scoped_error()
    : _handle(dew_error_create())
  {
  }
  ~scoped_error()
  {
    if (_handle)
      dew_error_destroy(_handle);
  }
  scoped_error(const scoped_error &) = delete;
  scoped_error &operator=(const scoped_error &) = delete;

  [[nodiscard]] dew_error_t *get() const { return _handle; }
  [[nodiscard]] bool set() const
  {
    if (!_handle)
      return false;
    int code = 0;
    const char *text = nullptr;
    size_t length = 0;
    dew_error_get_info(_handle, &code, &text, &length);
    return code != 0 || length != 0;
  }
  [[nodiscard]] error take(const char *fallback) const { return read_error(_handle, fallback); }

private:
  dew_error_t *_handle = nullptr;
};

// The two-call convention behind every `..._get_*_name(handle, index, buf, capacity)`: ask with a
// buffer, and grow if the answer did not fit. Starting at 256 means one call in practice.
template <class Fn> inline std::string out_string(Fn &&call)
{
  std::string buffer(256, '\\0');
  uint32_t written = call(buffer.data(), uint32_t(buffer.size()));
  if (written > buffer.size())
  {
    buffer.resize(written);
    written = call(buffer.data(), uint32_t(buffer.size()));
  }
  buffer.resize(written < buffer.size() ? written : buffer.size());
  return buffer;
}
} // namespace detail

'''

EPILOGUE = '''} // namespace dewpp
'''


# dew_error_t is folded into dewpp::error; a wrapper class for it would only ever be a detail of
# that, and its get_info out-param is the one result shape dewpp cannot express (the IR does not link
# the char* to its length, so nothing can rebuild a view from it).
_SUPPRESSED_CLASSES = {"dew_error_t"}

# These LOOK like failures to the IR -- void functions with a dew_error_t** -- but they are
# ACCESSORS: they hand back the error the handle is already holding (query_api.cpp's fill_error).
# Wrapping them as fallible would turn "ask what went wrong" into "this call went wrong". The set is
# closed and checked at generate time, so a new one has to be classified deliberately.
_ERROR_ACCESSORS = {"dew_dataset_get_error", "dew_request_get_error"}


class Generator:
    def __init__(self, api):
        self.api = api
        self.semantic = api["semantic"]
        self.raw = api["raw"]
        self.raw_functions = {fn["name"]: fn for fn in self.raw["functions"]}
        self.classes = [c for c in self.semantic["classes"] if c["handle_type"] not in _SUPPRESSED_CLASSES]
        self.by_handle = {c["handle_type"]: c for c in self.classes}
        # bound_name (CamelCase) -> C++ wrapper name (snake_case)
        self.wrapper_name = {c["handle_type"]: snake(c["bound_name"]) for c in self.classes}
        self.problems = []

    # -- helpers ---------------------------------------------------------------------------------

    def destroy_fn(self, cls):
        """The call that gives the handle back.

        Usually the IR's own destructor (a `*_destroy` name). Two handles release through differently
        named calls -- dew_dataset_close, dew_request_release -- and say so with `//= destroy:`,
        because guessing from a method list would be exactly the kind of inference that silently
        stops being true.
        """
        if cls["destructor"]:
            return cls["destructor"]["function"]
        declared = cls["annotations"].get("destroy")
        if isinstance(declared, str):
            return declared.strip()
        return None

    def method_is_destroy(self, cls, method):
        return method["function"] == self.destroy_fn(cls)

    # -- emission --------------------------------------------------------------------------------

    def emit_method(self, cls, method, mode):
        """mode: 'method' | 'factory' | 'free'. Returns source text, or None if unsupported."""
        fn = self.raw_functions[method["function"]]
        n_params = len(fn["params"])
        call_args = [None] * n_params
        params = []  # (cpp type, name)
        pre = []
        results = method["results"]

        if method["self_param"] is not None and mode == "method":
            call_args[method["self_param"]] = "_handle"

        convention = method["error_convention"]
        accessor = fn["name"] in _ERROR_ACCESSORS
        if accessor:
            # Verify the shape we are classifying by, so a future function cannot quietly join this
            # set by name alone.
            if fn["return_type"].get("name") != "void" or convention != "error_out_owned" or results:
                raise EmitError(f"{fn['name']}: listed as an error accessor but no longer looks like one")
            pre.append("detail::error_out error_;")
            call_args[method["error_param"]] = "error_.slot()"
        elif convention == "error_out_owned":
            pre.append("detail::error_out error_;")
            call_args[method["error_param"]] = "error_.slot()"
        elif convention == "error_arg_caller_owned":
            pre.append("detail::scoped_error error_;")
            call_args[method["error_param"]] = "error_.get()"

        out_string = next((r for r in results if r["role"] == "out_string"), None)

        for arg in method["args"]:
            role = arg["role"]
            name = san(arg["bound_name"])
            t = arg["type"]
            i = arg["c_params"][0]
            if role in ("scalar", "enum"):
                params.append((t["name"], name))
                call_args[i] = name
            elif role == "string_in":
                params.append(("std::string_view", name))
                call_args[i] = f"{name}.data()"
                call_args[arg["c_params"][1]] = f"static_cast<{arg['len_type']['name']}>({name}.size())"
            elif role == "array_in":
                if len(t["extents"]) != 1:
                    return None
                params.append((f"const std::array<{t['element']['name']}, {t['extents'][0]}> &", name))
                call_args[i] = f"{name}.data()"
            elif role == "struct_in":
                if arg.get("by_value"):
                    params.append((f"const {t['name']} &", name))
                    call_args[i] = name
                else:
                    record = t["pointee"]["name"]
                    params.append((f"const {record} &", name))
                    call_args[i] = f"&{name}" if t["pointee"]["const"] else f"const_cast<{record} *>(&{name})"
            elif role == "handle_in":
                other = self.wrapper_name.get(arg["handle"])
                if not other:
                    return None
                params.append((f"const {other} &", name))
                call_args[i] = f"{name}.handle()"
            elif role in ("callback_fn", "callback_struct"):
                # Straight through as the C type: the user_ptr is the caller's to spend, and a
                # std::function trampoline would need an owner the C API has nowhere to put.
                params.append((t["name"], name))
                call_args[i] = name
                if len(arg["c_params"]) > 1:
                    params.append(("void *", f"{name}_user_ptr"))
                    call_args[arg["c_params"][1]] = f"{name}_user_ptr"
            elif role == "buffer_array_in":
                element = arg["element_type"]
                count_i = arg["c_params"][1]
                count_cast = arg["count_type"]["name"]
                if element["kind"] != "record":
                    return None
                params.append((f"const std::vector<{element['name']}> &", name))
                call_args[i] = f"const_cast<{element['name']} *>({name}.data())"
                call_args[count_i] = f"static_cast<{count_cast}>({name}.size())"
            else:
                return None

        # results
        outs = []  # (name, cpp type, expr)
        gated = False
        returns_value = None
        rt = fn["return_type"]
        for result in results:
            role = result["role"]
            t = result["type"]
            if result["source"] == "return":
                if len(results) > 1 and t.get("name") == "bool":
                    gated = True
                else:
                    returns_value = t["name"]
                continue
            name = san(result["bound_name"]) + "_out"
            if role == "out_param":
                if result.get("borrowed"):
                    return None
                scalar = t["pointee"]["name"]
                pre.append(f"{scalar} {name}{{}};")
                call_args[result["c_params"][0]] = f"&{name}"
                outs.append((result["bound_name"], scalar, name))
            elif role == "array_out":
                element = t["element"]["name"]
                extent = t["extents"][0]
                pre.append(f"std::array<{element}, {extent}> {name}{{}};")
                call_args[result["c_params"][0]] = f"{name}.data()"
                outs.append((result["bound_name"], f"std::array<{element}, {extent}>", name))
            elif role == "struct_out":
                record = t["pointee"]["name"]
                pre.append(f"{record} {name}{{}};")
                call_args[result["c_params"][0]] = f"&{name}"
                outs.append((result["bound_name"], record, name))
            elif role == "out_string":
                pass
            else:
                return None

        # every C parameter must be accounted for
        unmapped = [idx for idx, value in enumerate(call_args) if value is None]
        if out_string:
            unmapped = [idx for idx in unmapped if idx not in out_string["c_params"]]
        if unmapped:
            return None

        # Constructors carry the CLASS's bound_name; as a static factory that would read
        # `converter::Converter(...)`. create_suffix distinguishes the overloads, so use it.
        if mode == "factory":
            suffix_ = method.get("create_suffix") or ""
            name = f"create_{suffix_}" if suffix_ else "create"
        else:
            name = san(method["bound_name"])
        signature_params = ", ".join(f"{cpp_type} {cpp_name}" for cpp_type, cpp_name in params)

        body = list(pre)

        # --- out_string methods return std::string and cannot fail ---
        if out_string:
            buf_i, cap_i = out_string["c_params"]
            inner = list(call_args)
            inner[buf_i] = "buffer_"
            inner[cap_i] = "capacity_"
            body.append("return detail::out_string([&](char *buffer_, uint32_t capacity_) {")
            body.append(f"  return {fn['name']}({', '.join(inner)});")
            body.append("});")
            return self._assemble(mode, cls, "std::string", name, signature_params, body, const=True)

        call = f"{fn['name']}({', '.join(call_args)})"

        if accessor:
            body.append(f"{call};")
            body.append("return error_.take_if_set();")
            return self._assemble(mode, cls, "std::optional<error>", name, signature_params, body, const=True)

        if mode == "factory":
            wrapper = self.wrapper_name[cls["handle_type"]]
            body.append(f"{cls['handle_type']} *handle_ = {call};")
            # The HANDLE is the success signal, not the error slot: a create can succeed and still
            # leave a non-null error behind, so checking the error first would report a phantom
            # failure. (generate_nanobind.py:527 encodes the same order.)
            body.append("if (!handle_)")
            if convention in ("error_out_owned", "error_arg_caller_owned"):
                body.append(f'  return std::unexpected(error_.take("{fn["name"]} failed"));')
            else:
                body.append(f'  return std::unexpected(error(-1, "{fn["name"]} failed"));')
            body.append(f"return {wrapper}(handle_);")
            return self._assemble(mode, cls, f"result<{wrapper}>", name, signature_params, body, static=True)

        # --- ordinary methods / free functions ---
        if gated:
            body.append(f"bool ok_ = {call};")
        elif returns_value:
            body.append(f"{returns_value} return_ = {call};")
        else:
            body.append(f"{call};")

        fails = convention in ("error_out_owned", "error_arg_caller_owned")
        if fails:
            body.append("if (error_.set())")
            body.append(f'  return std::unexpected(error_.take("{fn["name"]} failed"));')

        payload_type, payload_expr = self._payload(cls, method, outs, gated, returns_value)
        if payload_expr:
            body.append(f"return {payload_expr};")

        if fails:
            return_type = f"result<{payload_type}>" if payload_type != "void" else "status"
            if payload_type == "void":
                body.append("return {};")
        else:
            return_type = payload_type

        const = method["self_param"] is not None and mode == "method"
        return self._assemble(mode, cls, return_type, name, signature_params, body, const=const)

    def _payload(self, cls, method, outs, gated, returns_value):
        """What the method hands back, and the expression that builds it."""
        struct = self.result_struct_name(cls, method)
        if gated:
            if len(outs) == 1:
                inner = outs[0][1]
                return f"std::optional<{inner}>", f"ok_ ? std::optional<{inner}>({outs[0][2]}) : std::nullopt"
            fields = ", ".join(o[2] for o in outs)
            return f"std::optional<{struct}>", f"ok_ ? std::optional<{struct}>({struct}{{{fields}}}) : std::nullopt"
        if returns_value and not outs:
            return returns_value, "return_"
        if not returns_value and len(outs) == 1:
            return outs[0][1], outs[0][2]
        if not returns_value and not outs:
            return "void", None
        # several results: a small generated aggregate
        fields = ([("return", returns_value, "return_")] if returns_value else []) + outs
        return struct, f"{struct}{{{', '.join(f[2] for f in fields)}}}"

    def result_struct_name(self, cls, method):
        prefix = self.wrapper_name[cls["handle_type"]] + "_" if cls else ""
        return f"{prefix}{san(method['bound_name'])}_result"

    def result_struct(self, cls, method):
        """The aggregate for a method with more than one result, if it needs one."""
        results = method["results"]
        outs = []
        returns_value = None
        gated = False
        for r in results:
            if r["source"] == "return":
                if len(results) > 1 and r["type"].get("name") == "bool":
                    gated = True
                else:
                    returns_value = r["type"]["name"]
                continue
            role = r["role"]
            t = r["type"]
            if role == "out_param":
                outs.append((san(r["bound_name"]), t["pointee"]["name"]))
            elif role == "array_out":
                outs.append((san(r["bound_name"]), f"std::array<{t['element']['name']}, {t['extents'][0]}>"))
            elif role == "struct_out":
                outs.append((san(r["bound_name"]), t["pointee"]["name"]))
            elif role == "out_string":
                return None
            else:
                return None
        count = len(outs) + (1 if returns_value else 0)
        if count < 2:
            return None
        name = self.result_struct_name(cls, method)
        lines = [f"struct {name}", "{"]
        if returns_value:
            lines.append(f"  {returns_value} return_;")
        for field_name, field_type in outs:
            lines.append(f"  {field_type} {field_name};")
        lines += ["};"]
        return "\n".join(lines)

    def _assemble(self, mode, cls, return_type, name, params, body, static=False, const=False):
        """Returns (declaration, definition).

        They are SPLIT because a method body that calls `other.get()` on another wrapper needs that
        wrapper to be a complete type, and the classes reference each other in both directions. Every
        definition is therefore emitted out-of-line, after every class is closed -- which is also why
        they carry `inline`.
        """
        suffix = " const" if const else ""
        if mode == "free":
            head = f"inline {return_type} {name}({params}){suffix}"
            definition = "\n".join([head, "{"] + [f"  {line}" for line in body] + ["}"])
            return None, definition

        wrapper = self.wrapper_name[cls["handle_type"]]
        prefix = "static " if static else ""
        declaration = f"  {prefix}{return_type} {name}({params}){suffix};"
        head = f"inline {return_type} {wrapper}::{name}({params}){suffix}"
        definition = "\n".join([head, "{"] + [f"  {line}" for line in body] + ["}"])
        return declaration, definition

    # -- top level -------------------------------------------------------------------------------

    def emit_class(self, cls):
        handle = cls["handle_type"]
        wrapper = self.wrapper_name[handle]
        destroy = self.destroy_fn(cls)
        owning = destroy is not None

        lines = []
        # Result aggregates live at namespace scope, named <wrapper>_<method>_result, so the
        # out-of-line method bodies below can name them without qualification.
        for method in cls["constructors"] + cls["methods"]:
            if self.method_is_destroy(cls, method):
                continue
            aggregate = self.result_struct(cls, method)
            if aggregate:
                lines.append(aggregate)
                lines.append("")
        if cls["doc"]:
            for line in cls["doc"].splitlines():
                lines.append(f"// {line}".rstrip())
        if owning:
            lines.append(f"// Owns its {handle}: move-only, destroyed with {destroy}.")
        else:
            lines.append(f"// A BORROWED {handle} -- the library owns it. Copyable, destroys nothing, and valid only")
            lines.append("// for as long as whatever produced it says.")
        lines.append(f"class {wrapper}")
        lines.append("{")
        lines.append("public:")
        lines.append(f"  {wrapper}() = default;")
        lines.append(f"  explicit {wrapper}({handle} *handle)")
        lines.append("    : _handle(handle)")
        lines.append("  {")
        lines.append("  }")
        lines.append("")

        if owning:
            lines += [
                f"  ~{wrapper}() {{ reset(); }}",
                f"  {wrapper}({wrapper} &&other) noexcept",
                "    : _handle(other._handle)",
                "  {",
                "    other._handle = nullptr;",
                "  }",
                f"  {wrapper} &operator=({wrapper} &&other) noexcept",
                "  {",
                "    if (this != &other)",
                "    {",
                "      reset();",
                "      _handle = other._handle;",
                "      other._handle = nullptr;",
                "    }",
                "    return *this;",
                "  }",
                f"  {wrapper}(const {wrapper} &) = delete;",
                f"  {wrapper} &operator=(const {wrapper} &) = delete;",
                "",
                "  void reset()",
                "  {",
                "    if (_handle)",
                f"      {destroy}(_handle);",
                "    _handle = nullptr;",
                "  }",
                "",
                "  // Hand the raw handle back, giving up ownership.",
                f"  [[nodiscard]] {handle} *release()",
                "  {",
                f"    {handle} *handle = _handle;",
                "    _handle = nullptr;",
                "    return handle;",
                "  }",
                "",
            ]
        lines += [
            f"  // Named handle() rather than get(): several data sources already have a `get` method of",
            f"  // their own (dew_*_data_source_get), and the wrapper must not shadow it.",
            f"  [[nodiscard]] {handle} *handle() const {{ return _handle; }}",
            "  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }",
            "",
        ]

        emitted, skipped = 0, []
        definitions = []
        for method in cls["constructors"] + cls["methods"]:
            if self.method_is_destroy(cls, method):
                continue  # the destructor does this
            mode = "factory" if method in cls["constructors"] else "method"
            emitted_pair = self.emit_method(cls, method, mode)
            if emitted_pair is None:
                skipped.append(method["function"])
                continue
            declaration, definition = emitted_pair
            if method["doc"]:
                for line in method["doc"].splitlines():
                    lines.append(f"  // {line}".rstrip())
            lines.append(declaration)
            lines.append("")
            definitions.append(definition)
            emitted += 1

        if skipped:
            lines.append("  // Not wrapped -- call the C function directly with get():")
            for fn in skipped:
                lines.append(f"  //   {fn}")
            lines.append("")

        lines += ["private:", f"  {handle} *_handle = nullptr;", "};", ""]
        self.problems += [(cls["bound_name"], fn) for fn in skipped]
        return "\n".join(lines), definitions

    def generate(self):
        parts = [PROLOGUE]

        headers = []
        for kind in ("opaque_types", "enums", "structs", "callbacks", "functions", "macro_constants"):
            for entry in self.raw[kind]:
                if entry["header"] not in headers:
                    headers.append(entry["header"])
        for header in headers:
            parts.append(f"#include <{header}>\n")
        parts.append(STD_INCLUDES)
        parts.append("")
        parts.append(ERROR_TYPE)

        parts.append("// ---- enums, value structs and constants: aliases of the C declarations ----\n\n")
        for enum in self.semantic["enums"]:
            parts.append(f"using {snake(enum['bound_name'])} = {enum['c_name']};\n")
        parts.append("\n")
        for struct in self.semantic["value_structs"]:
            parts.append(f"using {snake(struct['bound_name'])} = {struct['c_name']};\n")
        parts.append("\n")
        for constant in self.semantic["constants"]:
            parts.append(f"inline constexpr auto {constant['bound_name'].lower()} = {constant['macro']};\n")
        parts.append("\n")

        parts.append("// ---- handles ----\n\n")
        # Forward declarations, so a method can take another wrapper by reference.
        for cls in self.classes:
            parts.append(f"class {self.wrapper_name[cls['handle_type']]};\n")
        parts.append("\n")
        all_definitions = []
        for cls in self.classes:
            body, definitions = self.emit_class(cls)
            parts.append(body)
            parts.append("\n")
            all_definitions += definitions

        parts.append("// ---- method bodies ----\n")
        parts.append("//\n")
        parts.append("// Out-of-line because a body that calls another wrapper's get() needs that wrapper to be a\n")
        parts.append("// complete type, and the classes reference each other in both directions.\n\n")
        for definition in all_definitions:
            parts.append(definition)
            parts.append("\n\n")

        if self.semantic["free_functions"]:
            parts.append("// ---- free functions ----\n\n")
            for fn in self.semantic["free_functions"]:
                emitted_pair = self.emit_method(None, fn, "free")
                if emitted_pair is None:
                    self.problems.append(("<free>", fn["function"]))
                    continue
                parts.append(emitted_pair[1])
                parts.append("\n\n")

        parts.append(EPILOGUE)
        return "".join(parts)


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--api", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--check", action="store_true", help="fail if --output is not what would be generated")
    args = parser.parse_args(argv)

    with open(args.api, "r", encoding="utf-8") as handle:
        api = json.load(handle)

    generator = Generator(api)
    text = generator.generate()

    if args.check:
        try:
            with open(args.output, "r", encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            current = None
        if current != text:
            print(f"cpp: {args.output} is stale -- rerun generate_cpp.py", file=sys.stderr)
            return 1
        print(f"cpp: {args.output} is up to date")
        return 0

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(text)

    wrapped = sum(1 for _ in generator.classes)
    print(f"cpp: {args.output} ({wrapped} classes, {len(generator.problems)} functions passed through)")
    for cls, fn in generator.problems:
        print(f"cpp:   not wrapped: {cls}.{fn}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
