/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/aabb_data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/aabb_data_source.h>
#include <dew/render/data_source.h>
#include <dew/render/renderer.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class aabb_data_source_t;

// Owns its dew_aabb_data_source_t: move-only, destroyed with dew_aabb_data_source_destroy.
class aabb_data_source_t
{
public:
  aabb_data_source_t() = default;
  explicit aabb_data_source_t(dew_aabb_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~aabb_data_source_t() { reset(); }
  aabb_data_source_t(aabb_data_source_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  aabb_data_source_t &operator=(aabb_data_source_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  aabb_data_source_t(const aabb_data_source_t &) = delete;
  aabb_data_source_t &operator=(const aabb_data_source_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_aabb_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_aabb_data_source_t *release()
  {
    dew_aabb_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_aabb_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<aabb_data_source_t> create(const renderer_t & renderer, const std::array<double, 3> & offset);

  dew_data_source_t get() const;

  int add_aabb(const std::array<double, 3> & min, const std::array<double, 3> & max) const;

  void remove_aabb(int id) const;

  void modify_aabb(int id, const std::array<double, 3> & min, const std::array<double, 3> & max) const;

  std::array<double, 3> get_center(int id) const;

private:
  dew_aabb_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<aabb_data_source_t> aabb_data_source_t::create(const renderer_t & renderer, const std::array<double, 3> & offset)
{
  dew_aabb_data_source_t *handle_ = dew_aabb_data_source_create(renderer.handle(), offset.data());
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_aabb_data_source_create failed"));
  return aabb_data_source_t(handle_);
}

inline dew_data_source_t aabb_data_source_t::get() const
{
  dew_data_source_t return_ = dew_aabb_data_source_get(_handle);
  return return_;
}

inline int aabb_data_source_t::add_aabb(const std::array<double, 3> & min, const std::array<double, 3> & max) const
{
  int return_ = dew_aabb_data_source_add_aabb(_handle, min.data(), max.data());
  return return_;
}

inline void aabb_data_source_t::remove_aabb(int id) const
{
  dew_aabb_data_source_remove_aabb(_handle, id);
}

inline void aabb_data_source_t::modify_aabb(int id, const std::array<double, 3> & min, const std::array<double, 3> & max) const
{
  dew_aabb_data_source_modify_aabb(_handle, id, min.data(), max.data());
}

inline std::array<double, 3> aabb_data_source_t::get_center(int id) const
{
  std::array<double, 3> center_out{};
  dew_aabb_data_source_get_center(_handle, id, center_out.data());
  return center_out;
}

} // namespace dewpp
