/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/buffer.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/buffer.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class buffer_t;

// A BORROWED dew_buffer_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class buffer_t
{
public:
  buffer_t() = default;
  explicit buffer_t(dew_buffer_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_buffer_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void set_rendered() const;

  void release_data() const;

private:
  dew_buffer_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline void buffer_t::set_rendered() const
{
  dew_buffer_set_rendered(_handle);
}

inline void buffer_t::release_data() const
{
  dew_buffer_release_data(_handle);
}

} // namespace dewpp
