/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/camera.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/aabb.h>
#include <dew/render/camera.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class camera_t;
class arcball_t;
class fps_t;

struct camera_perspective_properties_result_t
{
  double fov;
  double aspect;
  double near;
  double far;
};

// Owns its dew_camera_t: move-only, destroyed with dew_camera_destroy.
class camera_t
{
public:
  camera_t() = default;
  explicit camera_t(dew_camera_t *handle)
    : _handle(handle)
  {
  }

  ~camera_t() { reset(); }
  camera_t(camera_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  camera_t &operator=(camera_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  camera_t(const camera_t &) = delete;
  camera_t &operator=(const camera_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_camera_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_camera_t *release()
  {
    dew_camera_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_camera_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<camera_t> create();

  void look_at(const std::array<double, 3> & eye, const std::array<double, 3> & center, const std::array<double, 3> & up) const;

  void look_at_aabb(const dew_aabb_t & aabb, const std::array<double, 3> & direction, const std::array<double, 3> & up) const;

  std::array<double, 16> get_view_matrix() const;

  void set_view_matrix(const std::array<double, 16> & data) const;

  std::array<double, 16> get_perspective_matrix() const;

  void set_perspective_matrix(const std::array<double, 16> & data) const;

  void set_perspective(double fov, double width, double height, double near, double far) const;

  camera_perspective_properties_result_t perspective_properties() const;

  std::array<double, 3> get_eye() const;

  std::array<double, 3> get_forward() const;

private:
  dew_camera_t *_handle = nullptr;
};

// Owns its dew_arcball_t: move-only, destroyed with dew_arcball_destroy.
class arcball_t
{
public:
  arcball_t() = default;
  explicit arcball_t(dew_arcball_t *handle)
    : _handle(handle)
  {
  }

  ~arcball_t() { reset(); }
  arcball_t(arcball_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  arcball_t &operator=(arcball_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  arcball_t(const arcball_t &) = delete;
  arcball_t &operator=(const arcball_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_arcball_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_arcball_t *release()
  {
    dew_arcball_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_arcball_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<arcball_t> create(const camera_t & camera, const std::array<double, 3> & center);

  void reset() const;

  void detect_upside_down() const;

  void rotate(float normalized_dx, float normalized_dy, float normalized_dz) const;

  void pan(float normalized_dx, float normalized_dy) const;

  void pan_ground(float normalized_dx, float normalized_dy) const;

  void dolly(float normalized_dz) const;

  void zoom(float normalized_zoom) const;

  void set_up_axis(const std::array<double, 3> & up) const;

  std::array<double, 3> get_up_axis() const;

  std::array<double, 3> get_center() const;

private:
  dew_arcball_t *_handle = nullptr;
};

// Owns its dew_fps_t: move-only, destroyed with dew_fps_destroy.
class fps_t
{
public:
  fps_t() = default;
  explicit fps_t(dew_fps_t *handle)
    : _handle(handle)
  {
  }

  ~fps_t() { reset(); }
  fps_t(fps_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  fps_t &operator=(fps_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  fps_t(const fps_t &) = delete;
  fps_t &operator=(const fps_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_fps_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_fps_t *release()
  {
    dew_fps_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_fps_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<fps_t> create(const camera_t & camera);

  void reset() const;

  void rotate(float normalized_dx, float normalized_dy, float normalized_dz) const;

  void move(float dx, float dy, float dz) const;

private:
  dew_fps_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<camera_t> camera_t::create()
{
  dew_camera_t *handle_ = dew_camera_create();
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_camera_create failed"));
  return camera_t(handle_);
}

inline void camera_t::look_at(const std::array<double, 3> & eye, const std::array<double, 3> & center, const std::array<double, 3> & up) const
{
  dew_camera_look_at(_handle, eye.data(), center.data(), up.data());
}

inline void camera_t::look_at_aabb(const dew_aabb_t & aabb, const std::array<double, 3> & direction, const std::array<double, 3> & up) const
{
  dew_camera_look_at_aabb(_handle, const_cast<dew_aabb_t *>(&aabb), direction.data(), up.data());
}

inline std::array<double, 16> camera_t::get_view_matrix() const
{
  std::array<double, 16> data_out{};
  dew_camera_get_view_matrix(_handle, data_out.data());
  return data_out;
}

inline void camera_t::set_view_matrix(const std::array<double, 16> & data) const
{
  dew_camera_set_view_matrix(_handle, data.data());
}

inline std::array<double, 16> camera_t::get_perspective_matrix() const
{
  std::array<double, 16> data_out{};
  dew_camera_get_perspective_matrix(_handle, data_out.data());
  return data_out;
}

inline void camera_t::set_perspective_matrix(const std::array<double, 16> & data) const
{
  dew_camera_set_perspective_matrix(_handle, data.data());
}

inline void camera_t::set_perspective(double fov, double width, double height, double near, double far) const
{
  dew_camera_set_perspective(_handle, fov, width, height, near, far);
}

inline camera_perspective_properties_result_t camera_t::perspective_properties() const
{
  double fov_out{};
  double aspect_out{};
  double near_out{};
  double far_out{};
  dew_camera_perspective_properties(_handle, &fov_out, &aspect_out, &near_out, &far_out);
  return camera_perspective_properties_result_t{fov_out, aspect_out, near_out, far_out};
}

inline std::array<double, 3> camera_t::get_eye() const
{
  std::array<double, 3> eye_out{};
  dew_camera_get_eye(_handle, eye_out.data());
  return eye_out;
}

inline std::array<double, 3> camera_t::get_forward() const
{
  std::array<double, 3> forward_out{};
  dew_camera_get_forward(_handle, forward_out.data());
  return forward_out;
}

inline result_t<arcball_t> arcball_t::create(const camera_t & camera, const std::array<double, 3> & center)
{
  dew_arcball_t *handle_ = dew_arcball_create(camera.handle(), center.data());
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_arcball_create failed"));
  return arcball_t(handle_);
}

inline void arcball_t::reset() const
{
  dew_arcball_reset(_handle);
}

inline void arcball_t::detect_upside_down() const
{
  dew_arcball_detect_upside_down(_handle);
}

inline void arcball_t::rotate(float normalized_dx, float normalized_dy, float normalized_dz) const
{
  dew_arcball_rotate(_handle, normalized_dx, normalized_dy, normalized_dz);
}

inline void arcball_t::pan(float normalized_dx, float normalized_dy) const
{
  dew_arcball_pan(_handle, normalized_dx, normalized_dy);
}

inline void arcball_t::pan_ground(float normalized_dx, float normalized_dy) const
{
  dew_arcball_pan_ground(_handle, normalized_dx, normalized_dy);
}

inline void arcball_t::dolly(float normalized_dz) const
{
  dew_arcball_dolly(_handle, normalized_dz);
}

inline void arcball_t::zoom(float normalized_zoom) const
{
  dew_arcball_zoom(_handle, normalized_zoom);
}

inline void arcball_t::set_up_axis(const std::array<double, 3> & up) const
{
  dew_arcball_set_up_axis(_handle, up.data());
}

inline std::array<double, 3> arcball_t::get_up_axis() const
{
  std::array<double, 3> up_out{};
  dew_arcball_get_up_axis(_handle, up_out.data());
  return up_out;
}

inline std::array<double, 3> arcball_t::get_center() const
{
  std::array<double, 3> center_out{};
  dew_arcball_get_center(_handle, center_out.data());
  return center_out;
}

inline result_t<fps_t> fps_t::create(const camera_t & camera)
{
  dew_fps_t *handle_ = dew_fps_create(camera.handle());
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_fps_create failed"));
  return fps_t(handle_);
}

inline void fps_t::reset() const
{
  dew_fps_reset(_handle);
}

inline void fps_t::rotate(float normalized_dx, float normalized_dy, float normalized_dz) const
{
  dew_fps_rotate(_handle, normalized_dx, normalized_dy, normalized_dz);
}

inline void fps_t::move(float dx, float dy, float dz) const
{
  dew_fps_move(_handle, dx, dy, dz);
}

} // namespace dewpp
