/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/data_source.h>
#include <dew/render/draw_group.h>
#include <dew/render/renderer.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using frame_camera_t = dew_frame_camera_t;
using data_source_t = dew_data_source_t;

class to_render_t;

// A BORROWED dew_to_render_t -- the library owns it. Copyable, destroys nothing, and valid only
// for as long as whatever produced it says.
class to_render_t
{
public:
  to_render_t() = default;
  explicit to_render_t(dew_to_render_t *handle)
    : _handle(handle)
  {
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_to_render_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  void add_render_group(const dew_draw_group_t & draw_group) const;

private:
  dew_to_render_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline void to_render_t::add_render_group(const dew_draw_group_t & draw_group) const
{
  dew_to_render_add_render_group(_handle, draw_group);
}

} // namespace dewpp
