/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/environment_data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/data_source.h>
#include <dew/render/environment_data_source.h>
#include <dew/render/renderer.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class environment_data_source_t;

// Owns its dew_environment_data_source_t: move-only, destroyed with dew_environment_data_source_destroy.
class environment_data_source_t
{
public:
  environment_data_source_t() = default;
  explicit environment_data_source_t(dew_environment_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~environment_data_source_t() { reset(); }
  environment_data_source_t(environment_data_source_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  environment_data_source_t &operator=(environment_data_source_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  environment_data_source_t(const environment_data_source_t &) = delete;
  environment_data_source_t &operator=(const environment_data_source_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_environment_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_environment_data_source_t *release()
  {
    dew_environment_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_environment_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<environment_data_source_t> create(const renderer_t & renderer, double ground_z, double grid_size);

  dew_data_source_t get() const;

  void set_ground_z(double ground_z) const;

private:
  dew_environment_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<environment_data_source_t> environment_data_source_t::create(const renderer_t & renderer, double ground_z, double grid_size)
{
  dew_environment_data_source_t *handle_ = dew_environment_data_source_create(renderer.handle(), ground_z, grid_size);
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_environment_data_source_create failed"));
  return environment_data_source_t(handle_);
}

inline dew_data_source_t environment_data_source_t::get() const
{
  dew_data_source_t return_ = dew_environment_data_source_get(_handle);
  return return_;
}

inline void environment_data_source_t::set_ground_z(double ground_z) const
{
  dew_environment_data_source_set_ground_z(_handle, ground_z);
}

} // namespace dewpp
