/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/flat_points_data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/data_source.h>
#include <dew/render/flat_points_data_source.h>
#include <dew/render/renderer.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class flat_points_data_source_t;

struct flat_points_data_source_get_aabb_result_t
{
  std::array<double, 3> aabb_min;
  std::array<double, 3> aabb_max;
};

// Owns its dew_flat_points_data_source_t: move-only, destroyed with dew_flat_points_data_source_destroy.
class flat_points_data_source_t
{
public:
  flat_points_data_source_t() = default;
  explicit flat_points_data_source_t(dew_flat_points_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~flat_points_data_source_t() { reset(); }
  flat_points_data_source_t(flat_points_data_source_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  flat_points_data_source_t &operator=(flat_points_data_source_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  flat_points_data_source_t(const flat_points_data_source_t &) = delete;
  flat_points_data_source_t &operator=(const flat_points_data_source_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_flat_points_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_flat_points_data_source_t *release()
  {
    dew_flat_points_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_flat_points_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<flat_points_data_source_t> create(const renderer_t & renderer, std::string_view url);

  dew_data_source_t get() const;

  flat_points_data_source_get_aabb_result_t get_aabb() const;

private:
  dew_flat_points_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<flat_points_data_source_t> flat_points_data_source_t::create(const renderer_t & renderer, std::string_view url)
{
  dew_flat_points_data_source_t *handle_ = dew_flat_points_data_source_create(renderer.handle(), url.data(), static_cast<int>(url.size()));
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_flat_points_data_source_create failed"));
  return flat_points_data_source_t(handle_);
}

inline dew_data_source_t flat_points_data_source_t::get() const
{
  dew_data_source_t return_ = dew_flat_points_data_source_get(_handle);
  return return_;
}

inline flat_points_data_source_get_aabb_result_t flat_points_data_source_t::get_aabb() const
{
  std::array<double, 3> aabb_min_out{};
  std::array<double, 3> aabb_max_out{};
  dew_flat_points_get_aabb(_handle, aabb_min_out.data(), aabb_max_out.data());
  return flat_points_data_source_get_aabb_result_t{aabb_min_out, aabb_max_out};
}

} // namespace dewpp
