/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/renderer.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/camera.hpp>
#include <dew/render/data_source.h>
#include <dew/render/renderer.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using buffer_type_t = dew_buffer_type_t;
using texture_type_t = dew_texture_type_t;
using aabb_mesh_buffer_mapping_t = dew_aabb_mesh_buffer_mapping_t;
using skybox_buffer_mapping_t = dew_skybox_buffer_mapping_t;
using buffer_mapping_t = dew_buffer_mapping_t;
using dyn_points_buffer_mapping_t = dew_dyn_points_buffer_mapping_t;
using axis_gizmo_buffer_mapping_t = dew_axis_gizmo_buffer_mapping_t;
using origin_anchor_buffer_mapping_t = dew_origin_anchor_buffer_mapping_t;
using environment_buffer_mapping_t = dew_environment_buffer_mapping_t;
using node_bbox_buffer_mapping_t = dew_node_bbox_buffer_mapping_t;
using frame_t = dew_frame_t;
using renderer_callbacks_t = dew_renderer_callbacks_t;

class renderer_t;

// Owns its dew_renderer_t: move-only, destroyed with dew_renderer_destroy.
class renderer_t
{
public:
  renderer_t() = default;
  explicit renderer_t(dew_renderer_t *handle)
    : _handle(handle)
  {
  }

  ~renderer_t() { reset(); }
  renderer_t(renderer_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  renderer_t &operator=(renderer_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  renderer_t(const renderer_t &) = delete;
  renderer_t &operator=(const renderer_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_renderer_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_renderer_t *release()
  {
    dew_renderer_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_renderer_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<renderer_t> create();

  void add_camera(const camera_t & camera) const;

  void remove_camera(const camera_t & camera) const;

  dew_frame_t frame(const camera_t & camera) const;

  void set_callback(dew_renderer_callbacks_t callbacks, void * callbacks_user_ptr) const;

  void add_data_source(const dew_data_source_t & data_source) const;

  void remove_data_source(const dew_data_source_t & data_source) const;

private:
  dew_renderer_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<renderer_t> renderer_t::create()
{
  dew_renderer_t *handle_ = dew_renderer_create();
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_renderer_create failed"));
  return renderer_t(handle_);
}

inline void renderer_t::add_camera(const camera_t & camera) const
{
  dew_renderer_add_camera(_handle, camera.handle());
}

inline void renderer_t::remove_camera(const camera_t & camera) const
{
  dew_renderer_remove_camera(_handle, camera.handle());
}

inline dew_frame_t renderer_t::frame(const camera_t & camera) const
{
  dew_frame_t return_ = dew_renderer_frame(_handle, camera.handle());
  return return_;
}

inline void renderer_t::set_callback(dew_renderer_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_renderer_set_callback(_handle, callbacks, callbacks_user_ptr);
}

inline void renderer_t::add_data_source(const dew_data_source_t & data_source) const
{
  dew_renderer_add_data_source(_handle, data_source);
}

inline void renderer_t::remove_data_source(const dew_data_source_t & data_source) const
{
  dew_renderer_remove_data_source(_handle, data_source);
}

} // namespace dewpp
