/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/render/skybox_data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/core/error.hpp>
#include <dew/render/data_source.h>
#include <dew/render/renderer.hpp>
#include <dew/render/skybox_data_source.h>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using skybox_data_t = dew_skybox_data_t;

class skybox_data_source_t;

// Owns its dew_skybox_data_source_t: move-only, destroyed with dew_skybox_data_source_destroy.
class skybox_data_source_t
{
public:
  skybox_data_source_t() = default;
  explicit skybox_data_source_t(dew_skybox_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~skybox_data_source_t() { reset(); }
  skybox_data_source_t(skybox_data_source_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  skybox_data_source_t &operator=(skybox_data_source_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  skybox_data_source_t(const skybox_data_source_t &) = delete;
  skybox_data_source_t &operator=(const skybox_data_source_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_skybox_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_skybox_data_source_t *release()
  {
    dew_skybox_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_skybox_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<skybox_data_source_t> create(const renderer_t & renderer, const dew_skybox_data_t & data);

  dew_data_source_t get() const;

private:
  dew_skybox_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<skybox_data_source_t> skybox_data_source_t::create(const renderer_t & renderer, const dew_skybox_data_t & data)
{
  dew_skybox_data_source_t *handle_ = dew_skybox_data_source_create(renderer.handle(), data);
  if (!handle_)
    return std::unexpected(error_t(-1, "dew_skybox_data_source_create failed"));
  return skybox_data_source_t(handle_);
}

inline dew_data_source_t skybox_data_source_t::get() const
{
  dew_data_source_t return_ = dew_skybox_data_source_get(_handle);
  return return_;
}

} // namespace dewpp
