set(CURL_INCLUDE_DIRECTORIES ${CURL_INSTALL_DIR}/include)

set(CURL_IMPL_LIB_RELEASE ${CURL_INSTALL_DIR}/lib/libcurl_imp.lib)
set(CURL_IMPL_LIB_DEBUG ${CURL_INSTALL_DIR}/lib/libcurl-d_imp.lib)

set(CURL_LOCATION_RELEASE ${CURL_INSTALL_DIR}/bin/libcurl.dll)
set(CURL_LOCATION_DEBUG ${CURL_INSTALL_DIR}/bin/libcurl-d.dll)

if (NOT TARGET CURL::libcurl)
  add_library(CURL::libcurl SHARED IMPORTED)
  set_target_properties(CURL::libcurl
    PROPERTIES
    BUILD_EXTERNAL "On"
    BUILD_EXTERNAL_TARGET CURL_build
    BUILD_EXTERNAL_INTERFACE_INCLUDE_DIRECTORIES      "${CURL_INCLUDE_DIRECTORIES}"
    BUILD_EXTERNAL_IMPORTED_IMPLIB_RELEASE            "${CURL_IMPL_LIB_RELEASE}"
    BUILD_EXTERNAL_IMPORTED_IMPLIB_DEBUG              "${CURL_IMPL_LIB_DEBUG}"
    BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE          "${CURL_LOCATION_RELEASE}"
    BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG            "${CURL_LOCATION_DEBUG}"
    MAP_IMPORTED_CONFIG_MINSIZEREL     Release
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  )
endif()

