function(setWarningFlagsForTarget target)
  if (DISABLE_STRICT_WARNINGS)
    return()
  endif()
  if (MSVC)
    target_compile_options(${target} PRIVATE /W4 /WX)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -fms-extensions -Wunused-function -Werror=return-type -Wshadow-field -Wshadow-ivar -Wshadow-uncaptured-local)
  endif()
endfunction()
