/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/converter/converter.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/converter/converter.h>
#include <dew/core/error.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

// ---- aliases of the C declarations ----

using converter_conversion_status_t = dew_converter_conversion_status_t;
using converter_open_file_semantics_t = dew_converter_open_file_semantics_t;
using converter_compression_t = dew_converter_compression_t;
using converter_header_t = dew_converter_header_t;
using converter_file_pre_init_info_t = dew_converter_file_pre_init_info_t;
using converter_file_convert_callbacks_t = dew_converter_file_convert_callbacks_t;
using converter_runtime_callbacks_t = dew_converter_runtime_callbacks_t;
using converter_upload_callbacks_t = dew_converter_upload_callbacks_t;
using converter_upload_state_t = dew_converter_upload_state_t;
using converter_buffer_callbacks_t = dew_converter_buffer_callbacks_t;
using converter_str_buffer_t = dew_converter_str_buffer;
using converter_attribute_stats_t = dew_converter_attribute_stats_t;
using converter_stats_t = dew_converter_stats_t;
using converter_io_stats_t = dew_converter_io_stats_t;
using converter_perf_stats_t = dew_converter_perf_stats_t;

class converter_t;

// Owns its dew_converter_t: move-only, destroyed with dew_converter_destroy.
class converter_t
{
public:
  converter_t() = default;
  explicit converter_t(dew_converter_t *handle)
    : _handle(handle)
  {
  }

  ~converter_t() { reset(); }
  converter_t(converter_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  converter_t &operator=(converter_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  converter_t(const converter_t &) = delete;
  converter_t &operator=(const converter_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_converter_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_converter_t *release()
  {
    dew_converter_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_converter_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<converter_t> create(std::string_view cache_filename, dew_converter_open_file_semantics_t open_file_semantics);

  //  As dew_converter_create, but first applies `connection` (a vendor connection string -- credentials /
  //  endpoint / region; see connection_cli.h + vio connection_string.h) for the output URL's provider, so a
  //  dataset can be written directly to a cloud store. `connection` may be null/empty for local outputs or
  //  when credentials come from the environment. `open_file_semantics` is typically truncate.
  static result_t<converter_t> create_with_connection(std::string_view url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics);

  //  Destination mode: convert into a LOCAL cache file (`cache_path`, a bare path or file:// URL) while
  //  finalized subtrees upload incrementally to `destination_url` (s3:// az:// dir://; DEW2 layout).
  //  The cache stays a valid, renderable DEW at every checkpoint; blobs already uploaded are evicted
  //  from it under the cache cap (see dew_converter_set_cache_max_bytes), and when the disk runs out
  //  mid-conversion, unfinished data spills to the destination's spill/ area and is fetched back on
  //  demand. A null/empty destination degrades to dew_converter_create. `connection` carries the
  //  destination's credentials (null/empty = environment). Reopening the same cache+destination resumes:
  //  committed bands are never re-uploaded (a destination belonging to a different dataset generation is
  //  refused via the embedded uuid).
  static result_t<converter_t> create_with_destination(std::string_view cache_path, std::string_view destination_url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics);

  //  Cache-file resident-bytes cap for destination mode. 0 = unlimited (the default). Callable any
  //  time; lowering it triggers eviction/spill passes.
  void set_cache_max_bytes(uint64_t max_bytes) const;

  //  In-RAM decompressed read-cache budget (default 256MB). Also the seam a render/query consumer tunes.
  void set_read_cache_bytes(uint64_t max_bytes) const;

  void set_upload_callbacks(dew_converter_upload_callbacks_t callbacks, void * callbacks_user_ptr) const;

  //  Snapshot of upload/cache-tier state (approximate counters; safe any time). Returns false when the
  //  converter has no destination configured.
  std::optional<dew_converter_upload_state_t> get_upload_state() const;

  //  Wait until conversion is complete and the cache file is a fully checkpointed, valid DEW --
  //  uploads may still be in flight (contrast dew_converter_wait_idle, which also drains them).
  void wait_local_complete() const;

  void set_file_converter_callbacks(dew_converter_file_convert_callbacks_t callbacks) const;

  void set_runtime_callbacks(dew_converter_runtime_callbacks_t callbacks, void * callbacks_user_ptr) const;

  void set_compression(dew_converter_compression_t compression) const;

  void set_store_original_order(bool store) const;

  void set_compression_level(int level) const;

  //  Set the target points per octree node. This doubles as the read/sort chunk size, so it is the main
  //  control over stored blob size (one node ~ one compressed blob per attribute). Default 200000. Must be
  //  called before dew_converter_add_data_file.
  void set_node_point_limit(uint32_t points) const;

  //  Explicitly pin the octree coordinate scale (a single value used for all three axes). Without this the
  //  converter adopts the finest native scale of the first batch of input files (LAS header scale), falling
  //  back to 0.00025 when the source reports none. Must be called before dew_converter_add_data_file.
  void set_tree_scale(double scale) const;

  //  LOD nodes carry only the visual attributes (position + rgb/intensity/classification) by default;
  //  pass 1 to duplicate EVERY source attribute into every LOD level (the pre-slimming behavior, at a
  //  substantial size cost). Must be called before dew_converter_add_data_file.
  void set_lod_all_attributes(uint8_t all) const;

  //  Read/sort chunk byte target (default 64 MiB): the converter ingests each input in chunks of about
  //  this many bytes (computed from the file's per-point width, never below the node point limit,
  //  capped at 8M points per chunk). Larger chunks amortize source reads and sorting; the octree still
  //  subdivides to node_point_limit leaves and finalized leaves are rewritten into per-node units.
  //  Must be called before dew_converter_add_data_file.
  void set_read_chunk_bytes(uint64_t bytes) const;

  //  May block on ingest backpressure, so Python bindings must release the GIL around it.
  void add_data_file(const std::vector<dew_converter_str_buffer> & buffers) const;

  void wait_idle() const;

  dew_converter_conversion_status_t status() const;

  std::optional<dew_converter_stats_t> get_compression_stats() const;

  std::optional<dew_converter_perf_stats_t> get_perf_stats() const;

  std::optional<dew_converter_perf_stats_t> get_live_perf_stats() const;

private:
  dew_converter_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<converter_t> converter_t::create(std::string_view cache_filename, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out_t error_;
  dew_converter_t *handle_ = dew_converter_create(cache_filename.data(), static_cast<uint64_t>(cache_filename.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create failed"));
  return converter_t(handle_);
}

inline result_t<converter_t> converter_t::create_with_connection(std::string_view url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out_t error_;
  dew_converter_t *handle_ = dew_converter_create_with_connection(url.data(), static_cast<uint64_t>(url.size()), connection.data(), static_cast<uint64_t>(connection.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create_with_connection failed"));
  return converter_t(handle_);
}

inline result_t<converter_t> converter_t::create_with_destination(std::string_view cache_path, std::string_view destination_url, std::string_view connection, dew_converter_open_file_semantics_t open_file_semantics)
{
  detail::error_out_t error_;
  dew_converter_t *handle_ = dew_converter_create_with_destination(cache_path.data(), static_cast<uint64_t>(cache_path.size()), destination_url.data(), static_cast<uint64_t>(destination_url.size()), connection.data(), static_cast<uint64_t>(connection.size()), open_file_semantics, error_.slot());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_create_with_destination failed"));
  return converter_t(handle_);
}

inline void converter_t::set_cache_max_bytes(uint64_t max_bytes) const
{
  dew_converter_set_cache_max_bytes(_handle, max_bytes);
}

inline void converter_t::set_read_cache_bytes(uint64_t max_bytes) const
{
  dew_converter_set_read_cache_bytes(_handle, max_bytes);
}

inline void converter_t::set_upload_callbacks(dew_converter_upload_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_converter_set_upload_callbacks(_handle, callbacks, callbacks_user_ptr);
}

inline std::optional<dew_converter_upload_state_t> converter_t::get_upload_state() const
{
  dew_converter_upload_state_t state_out{};
  bool ok_ = dew_converter_get_upload_state(_handle, &state_out);
  return ok_ ? std::optional<dew_converter_upload_state_t>(state_out) : std::nullopt;
}

inline void converter_t::wait_local_complete() const
{
  dew_converter_wait_local_complete(_handle);
}

inline void converter_t::set_file_converter_callbacks(dew_converter_file_convert_callbacks_t callbacks) const
{
  dew_converter_set_file_converter_callbacks(_handle, callbacks);
}

inline void converter_t::set_runtime_callbacks(dew_converter_runtime_callbacks_t callbacks, void * callbacks_user_ptr) const
{
  dew_converter_set_runtime_callbacks(_handle, callbacks, callbacks_user_ptr);
}

inline void converter_t::set_compression(dew_converter_compression_t compression) const
{
  dew_converter_set_compression(_handle, compression);
}

inline void converter_t::set_store_original_order(bool store) const
{
  dew_converter_set_store_original_order(_handle, store);
}

inline void converter_t::set_compression_level(int level) const
{
  dew_converter_set_compression_level(_handle, level);
}

inline void converter_t::set_node_point_limit(uint32_t points) const
{
  dew_converter_set_node_point_limit(_handle, points);
}

inline void converter_t::set_tree_scale(double scale) const
{
  dew_converter_set_tree_scale(_handle, scale);
}

inline void converter_t::set_lod_all_attributes(uint8_t all) const
{
  dew_converter_set_lod_all_attributes(_handle, all);
}

inline void converter_t::set_read_chunk_bytes(uint64_t bytes) const
{
  dew_converter_set_read_chunk_bytes(_handle, bytes);
}

inline void converter_t::add_data_file(const std::vector<dew_converter_str_buffer> & buffers) const
{
  dew_converter_add_data_file(_handle, const_cast<dew_converter_str_buffer *>(buffers.data()), static_cast<uint32_t>(buffers.size()));
}

inline void converter_t::wait_idle() const
{
  dew_converter_wait_idle(_handle);
}

inline dew_converter_conversion_status_t converter_t::status() const
{
  dew_converter_conversion_status_t return_ = dew_converter_status(_handle);
  return return_;
}

inline std::optional<dew_converter_stats_t> converter_t::get_compression_stats() const
{
  dew_converter_stats_t stats_out{};
  bool ok_ = dew_converter_get_compression_stats(_handle, &stats_out);
  return ok_ ? std::optional<dew_converter_stats_t>(stats_out) : std::nullopt;
}

inline std::optional<dew_converter_perf_stats_t> converter_t::get_perf_stats() const
{
  dew_converter_perf_stats_t perf_stats_out{};
  bool ok_ = dew_converter_get_perf_stats(_handle, &perf_stats_out);
  return ok_ ? std::optional<dew_converter_perf_stats_t>(perf_stats_out) : std::nullopt;
}

inline std::optional<dew_converter_perf_stats_t> converter_t::get_live_perf_stats() const
{
  dew_converter_perf_stats_t perf_stats_out{};
  bool ok_ = dew_converter_get_live_perf_stats(_handle, &perf_stats_out);
  return ok_ ? std::optional<dew_converter_perf_stats_t>(perf_stats_out) : std::nullopt;
}

} // namespace dewpp
