/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/converter/converter_data_source.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/converter/converter_data_source.h>
#include <dew/core/error.hpp>
#include <dew/render/data_source.h>
#include <dew/render/renderer.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

class converter_data_source_t;

struct converter_data_source_get_memory_stats_result_t
{
  uint64_t heap_bytes;
  uint64_t heap_max;
  uint64_t budget_bytes;
  uint64_t backlog_bytes;
  uint64_t read_cache_bytes;
  uint64_t resident_cpu_bytes;
  uint32_t brake_level;
};

struct converter_data_source_get_frame_timings_result_t
{
  double tree_walk_ms;
  double buffer_reconciliation_ms;
  double gpu_upload_ms;
  double refine_strategy_ms;
  double frontier_scheduling_ms;
  double draw_emission_ms;
  double eviction_ms;
  double total_ms;
  int registry_node_count;
  int active_set_size;
  int nodes_drawn;
  int transitioning_count;
  int nodes_evicted;
  int nodes_reconcile_destroyed;
  int walker_node_count;
  uint64_t walker_total_points;
  int walker_trees_to_load;
  int io_in_flight;
};

struct converter_data_source_get_virtual_stats_result_t
{
  uint32_t promoted;
  uint64_t gpu_bytes;
  uint64_t resident_cpu_bytes;
  uint32_t nodes_drawn;
};

struct converter_data_source_get_tight_aabb_result_t
{
  std::array<double, 3> min;
  std::array<double, 3> max;
};

// Owns its dew_converter_data_source_t: move-only, destroyed with dew_converter_data_source_destroy.
class converter_data_source_t
{
public:
  converter_data_source_t() = default;
  explicit converter_data_source_t(dew_converter_data_source_t *handle)
    : _handle(handle)
  {
  }

  ~converter_data_source_t() { reset(); }
  converter_data_source_t(converter_data_source_t &&other) noexcept
    : _handle(other._handle)
  {
    other._handle = nullptr;
  }
  converter_data_source_t &operator=(converter_data_source_t &&other) noexcept
  {
    if (this != &other)
    {
      reset();
      _handle = other._handle;
      other._handle = nullptr;
    }
    return *this;
  }
  converter_data_source_t(const converter_data_source_t &) = delete;
  converter_data_source_t &operator=(const converter_data_source_t &) = delete;

  void reset()
  {
    if (_handle)
      dew_converter_data_source_destroy(_handle);
    _handle = nullptr;
  }

  // Hand the raw handle back, giving up ownership.
  [[nodiscard]] dew_converter_data_source_t *release()
  {
    dew_converter_data_source_t *handle = _handle;
    _handle = nullptr;
    return handle;
  }

  // Named handle() rather than get(): several data sources already have a `get` method of
  // their own (dew_*_data_source_get), and the wrapper must not shadow it.
  [[nodiscard]] dew_converter_data_source_t *handle() const { return _handle; }
  [[nodiscard]] explicit operator bool() const { return _handle != nullptr; }

  static result_t<converter_data_source_t> create(std::string_view url, const renderer_t & renderer);

  //  As dew_converter_data_source_create, but first applies `connection` (a vendor connection string --
  //  credentials / endpoint / region; same grammar/keys as dew_converter_create_with_connection, see vio
  //  connection_string.h) for the dataset URL's provider, so a dataset can be streamed directly from a cloud
  //  store (s3://bucket/prefix, az://container/prefix). `connection` may be null/empty for local files
  //  (file://, bare paths) or when credentials come from the AWS_*/AZURE_* environment; for a public bucket
  //  pass "anonymous=true" (optionally with "region=..."). A no-op for local/dir/mem URLs.
  static result_t<converter_data_source_t> create_with_connection(std::string_view url, std::string_view connection, const renderer_t & renderer);

  dew_data_source_t get() const;

  void request_aabb(dew_converter_data_source_request_aabb_callback_t callback, void * callback_user_ptr) const;

  uint32_t attribute_count() const;

  std::string get_attribute_name(int index) const;

  void set_rendered_attribute(std::string_view name) const;

  void set_viewport(int width, int height) const;

  void set_pixel_error_threshold(double threshold) const;

  void set_render_density_px(double density_px) const;

  void set_gpu_memory_budget(size_t budget_bytes) const;

  void set_upload_budget_per_frame(size_t budget_bytes) const;

  void set_max_in_flight_io(int max_requests) const;

  //  One total CPU-memory budget for the streaming renderer. Internally derived into the read-cache size, the
  //  decoded-backlog byte cap (new IO is refused while estimated in-flight + decoded-awaiting-upload bytes
  //  exceed it), the virtual-subtree CPU-resident budget, and a clamp on max_in_flight_io (see
  //  memory_budget.hpp for the formula). GPU memory has its own budget
  //  (dew_converter_data_source_set_gpu_memory_budget) -- GL buffers live outside this heap. The default
  //  (1GB) reproduces the historical sub-budget defaults. Values below 64MB are clamped up to 64MB.
  void set_memory_budget(uint64_t total_bytes) const;

  uint64_t get_memory_budget() const;

  //  Observability for the memory budget and the wasm heap-pressure brake. heap_bytes/heap_max are the wasm
  //  heap size and its link-time ceiling as probed on the last rendered frame (0/0 on native); backlog_bytes
  //  is the estimated CPU held by in-flight + decoded-awaiting-upload nodes last frame; brake_level is
  //  0 none / 1 high (>=80% of ceiling) / 2 critical (>=90%). Any out-pointer may be null.
  converter_data_source_get_memory_stats_result_t get_memory_stats() const;

  uint64_t get_points_rendered() const;

  uint8_t is_animating() const;

  converter_data_source_get_frame_timings_result_t get_frame_timings() const;

  void set_debug_transitions(uint8_t enabled) const;

  //  Virtual subnodes (render-time balanced LOD for spanning leaves). Toggling off tears every virtual cut down
  //  and falls the leaves back to their monoliths, so it is a live A/B on one camera path.
  void set_enable_virtual_subtrees(uint8_t enabled) const;

  uint8_t get_enable_virtual_subtrees() const;

  //  Observability: how many spanning leaves are currently promoted, the GPU bytes their virtual nodes hold, the
  //  CPU bytes their resident sources pin, and how many virtual nodes were drawn last frame.
  converter_data_source_get_virtual_stats_result_t get_virtual_stats() const;

  void set_show_bounding_boxes(uint8_t enabled) const;

  dew_data_source_t get_bbox_data_source() const;

  converter_data_source_get_tight_aabb_result_t get_tight_aabb() const;

private:
  dew_converter_data_source_t *_handle = nullptr;
};

// ---- method bodies ----
//
// Out-of-line because a body that calls another wrapper's handle() needs that wrapper to be
// a complete type, and classes in one header can reference each other in both directions.

inline result_t<converter_data_source_t> converter_data_source_t::create(std::string_view url, const renderer_t & renderer)
{
  detail::scoped_error_t error_;
  dew_converter_data_source_t *handle_ = dew_converter_data_source_create(url.data(), static_cast<uint32_t>(url.size()), error_.get(), renderer.handle());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_data_source_create failed"));
  return converter_data_source_t(handle_);
}

inline result_t<converter_data_source_t> converter_data_source_t::create_with_connection(std::string_view url, std::string_view connection, const renderer_t & renderer)
{
  detail::scoped_error_t error_;
  dew_converter_data_source_t *handle_ = dew_converter_data_source_create_with_connection(url.data(), static_cast<uint32_t>(url.size()), connection.data(), static_cast<uint32_t>(connection.size()), error_.get(), renderer.handle());
  if (!handle_)
    return std::unexpected(error_.take("dew_converter_data_source_create_with_connection failed"));
  return converter_data_source_t(handle_);
}

inline dew_data_source_t converter_data_source_t::get() const
{
  dew_data_source_t return_ = dew_converter_data_source_get(_handle);
  return return_;
}

inline void converter_data_source_t::request_aabb(dew_converter_data_source_request_aabb_callback_t callback, void * callback_user_ptr) const
{
  dew_converter_data_source_request_aabb(_handle, callback, callback_user_ptr);
}

inline uint32_t converter_data_source_t::attribute_count() const
{
  uint32_t return_ = dew_converter_data_attribute_count(_handle);
  return return_;
}

inline std::string converter_data_source_t::get_attribute_name(int index) const
{
  return detail::out_string([&](char *buffer_, uint32_t capacity_) {
    return dew_converter_data_get_attribute_name(_handle, index, buffer_, capacity_);
  });
}

inline void converter_data_source_t::set_rendered_attribute(std::string_view name) const
{
  dew_converter_data_set_rendered_attribute(_handle, name.data(), static_cast<uint32_t>(name.size()));
}

inline void converter_data_source_t::set_viewport(int width, int height) const
{
  dew_converter_data_source_set_viewport(_handle, width, height);
}

inline void converter_data_source_t::set_pixel_error_threshold(double threshold) const
{
  dew_converter_data_source_set_pixel_error_threshold(_handle, threshold);
}

inline void converter_data_source_t::set_render_density_px(double density_px) const
{
  dew_converter_data_source_set_render_density_px(_handle, density_px);
}

inline void converter_data_source_t::set_gpu_memory_budget(size_t budget_bytes) const
{
  dew_converter_data_source_set_gpu_memory_budget(_handle, budget_bytes);
}

inline void converter_data_source_t::set_upload_budget_per_frame(size_t budget_bytes) const
{
  dew_converter_data_source_set_upload_budget_per_frame(_handle, budget_bytes);
}

inline void converter_data_source_t::set_max_in_flight_io(int max_requests) const
{
  dew_converter_data_source_set_max_in_flight_io(_handle, max_requests);
}

inline void converter_data_source_t::set_memory_budget(uint64_t total_bytes) const
{
  dew_converter_data_source_set_memory_budget(_handle, total_bytes);
}

inline uint64_t converter_data_source_t::get_memory_budget() const
{
  uint64_t return_ = dew_converter_data_source_get_memory_budget(_handle);
  return return_;
}

inline converter_data_source_get_memory_stats_result_t converter_data_source_t::get_memory_stats() const
{
  uint64_t heap_bytes_out{};
  uint64_t heap_max_out{};
  uint64_t budget_bytes_out{};
  uint64_t backlog_bytes_out{};
  uint64_t read_cache_bytes_out{};
  uint64_t resident_cpu_bytes_out{};
  uint32_t brake_level_out{};
  dew_converter_data_source_get_memory_stats(_handle, &heap_bytes_out, &heap_max_out, &budget_bytes_out, &backlog_bytes_out, &read_cache_bytes_out, &resident_cpu_bytes_out, &brake_level_out);
  return converter_data_source_get_memory_stats_result_t{heap_bytes_out, heap_max_out, budget_bytes_out, backlog_bytes_out, read_cache_bytes_out, resident_cpu_bytes_out, brake_level_out};
}

inline uint64_t converter_data_source_t::get_points_rendered() const
{
  uint64_t return_ = dew_converter_data_source_get_points_rendered(_handle);
  return return_;
}

inline uint8_t converter_data_source_t::is_animating() const
{
  uint8_t return_ = dew_converter_data_source_is_animating(_handle);
  return return_;
}

inline converter_data_source_get_frame_timings_result_t converter_data_source_t::get_frame_timings() const
{
  double tree_walk_ms_out{};
  double buffer_reconciliation_ms_out{};
  double gpu_upload_ms_out{};
  double refine_strategy_ms_out{};
  double frontier_scheduling_ms_out{};
  double draw_emission_ms_out{};
  double eviction_ms_out{};
  double total_ms_out{};
  int registry_node_count_out{};
  int active_set_size_out{};
  int nodes_drawn_out{};
  int transitioning_count_out{};
  int nodes_evicted_out{};
  int nodes_reconcile_destroyed_out{};
  int walker_node_count_out{};
  uint64_t walker_total_points_out{};
  int walker_trees_to_load_out{};
  int io_in_flight_out{};
  dew_converter_data_source_get_frame_timings(_handle, &tree_walk_ms_out, &buffer_reconciliation_ms_out, &gpu_upload_ms_out, &refine_strategy_ms_out, &frontier_scheduling_ms_out, &draw_emission_ms_out, &eviction_ms_out, &total_ms_out, &registry_node_count_out, &active_set_size_out, &nodes_drawn_out, &transitioning_count_out, &nodes_evicted_out, &nodes_reconcile_destroyed_out, &walker_node_count_out, &walker_total_points_out, &walker_trees_to_load_out, &io_in_flight_out);
  return converter_data_source_get_frame_timings_result_t{tree_walk_ms_out, buffer_reconciliation_ms_out, gpu_upload_ms_out, refine_strategy_ms_out, frontier_scheduling_ms_out, draw_emission_ms_out, eviction_ms_out, total_ms_out, registry_node_count_out, active_set_size_out, nodes_drawn_out, transitioning_count_out, nodes_evicted_out, nodes_reconcile_destroyed_out, walker_node_count_out, walker_total_points_out, walker_trees_to_load_out, io_in_flight_out};
}

inline void converter_data_source_t::set_debug_transitions(uint8_t enabled) const
{
  dew_converter_data_source_set_debug_transitions(_handle, enabled);
}

inline void converter_data_source_t::set_enable_virtual_subtrees(uint8_t enabled) const
{
  dew_converter_data_source_set_enable_virtual_subtrees(_handle, enabled);
}

inline uint8_t converter_data_source_t::get_enable_virtual_subtrees() const
{
  uint8_t return_ = dew_converter_data_source_get_enable_virtual_subtrees(_handle);
  return return_;
}

inline converter_data_source_get_virtual_stats_result_t converter_data_source_t::get_virtual_stats() const
{
  uint32_t promoted_out{};
  uint64_t gpu_bytes_out{};
  uint64_t resident_cpu_bytes_out{};
  uint32_t nodes_drawn_out{};
  dew_converter_data_source_get_virtual_stats(_handle, &promoted_out, &gpu_bytes_out, &resident_cpu_bytes_out, &nodes_drawn_out);
  return converter_data_source_get_virtual_stats_result_t{promoted_out, gpu_bytes_out, resident_cpu_bytes_out, nodes_drawn_out};
}

inline void converter_data_source_t::set_show_bounding_boxes(uint8_t enabled) const
{
  dew_converter_data_source_set_show_bounding_boxes(_handle, enabled);
}

inline dew_data_source_t converter_data_source_t::get_bbox_data_source() const
{
  dew_data_source_t return_ = dew_converter_data_source_get_bbox_data_source(_handle);
  return return_;
}

inline converter_data_source_get_tight_aabb_result_t converter_data_source_t::get_tight_aabb() const
{
  std::array<double, 3> min_out{};
  std::array<double, 3> max_out{};
  dew_converter_data_source_get_tight_aabb(_handle, min_out.data(), max_out.data());
  return converter_data_source_get_tight_aabb_result_t{min_out, max_out};
}

} // namespace dewpp
