/* GENERATED by tools/bindgen/generate_cpp.py -- do not edit.
 *
 * dew/converter/laszip_file_convert_callbacks.hpp -- the C++ wrapper for the C declarations in the header of the same name.
 *
 * The layout mirrors the C headers, so the wrapper for <dew/access/query.h> is
 * <dew/access/query.hpp>. Include <dew/dewpp.hpp> for all of them at once; that header also carries
 * the overview of how the wrapper works.
 */
#pragma once

#include <dew/converter/converter.h>
#include <dew/converter/laszip_file_convert_callbacks.h>
#include <dew/core/error.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace dewpp
{

inline dew_converter_file_convert_callbacks_t laszip_callbacks()
{
  dew_converter_file_convert_callbacks_t return_ = dew_laszip_callbacks();
  return return_;
}

} // namespace dewpp
